using Npgsql;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using GriefLedger.Rollback;
using NpgsqlTypes;
using Vintagestory.API.Common;
using Vintagestory.API.Config;
using Vintagestory.API.MathTools;
using Vintagestory.API.Server;

namespace GriefLedger;

public sealed class DatabaseWriterQueueFullException : InvalidOperationException {
    public DatabaseWriterQueueFullException(int capacity)
        : base($"The database writer queue reached its bounded capacity of {capacity} work items.") {
        Capacity = capacity;
    }
    public int Capacity { get; }
}

public sealed class DatabaseWriterUnavailableException : InvalidOperationException {
    public DatabaseWriterUnavailableException(Exception terminalFailure)
        : base("The database writer previously failed and is unavailable for this database lifetime.",
            terminalFailure ?? throw new ArgumentNullException(nameof(terminalFailure))) { }
}

public class Database : IDisposable {
    public const int DefaultWriterQueueCapacity = 64;
    private int logLimit = 4;
    private readonly NpgsqlDataSource dataSource;

    private readonly Thread workerThread;
    private readonly BlockingCollection<WriterWorkItem> databaseTasks;
    private readonly object lifecycleLock = new object();
    private readonly ManualResetEventSlim readsDrained = new ManualResetEventSlim(true);
    private bool acceptingWrites = true;
    private bool acceptingReads = true;
    private int activeReads;
    private bool disposed;
    private long rejectedWriterWorkCount;
    private long lastQueueFullLogTicks;
    private Exception? terminalWriterFailure;
    private int activeWriterWorkCount;

    private sealed class WriterWorkItem {
        public required Action<NpgsqlConnection> Execute { get; init; }
        public Action? Complete { get; init; }
        public Action<Exception>? Fail { get; init; }
        public bool IsBarrier { get; init; }
    }

    private const string CreatePlayersTable = @"CREATE TABLE IF NOT EXISTS players (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        playeruid TEXT UNIQUE,
        last_playername TEXT
    )";
    private const string CreateBlockLogsTable = @"CREATE TABLE IF NOT EXISTS blocklogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        actiontype INTEGER,
        block TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        x INTEGER,
        y INTEGER,
        z INTEGER,
        oldblockid INTEGER
    )";
    private const string CreateEntityLogsTable = @"CREATE TABLE IF NOT EXISTS entitylogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        actiontype INTEGER,
        entityname TEXT,
        entityid TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        x INTEGER,
        y INTEGER,
        z INTEGER
    )";
    private const string CreateContainerLogsTable = @"CREATE TABLE IF NOT EXISTS containerlogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        containerid TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        quantity INTEGER,
        actiontype INTEGER
    )";
    private static readonly string CreateBlockMutationLogsTable = $@"CREATE TABLE IF NOT EXISTS blockmutationlogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT NOT NULL,
        player_id BIGINT NULL,
        entry_kind INTEGER NOT NULL,
        action_kind INTEGER NOT NULL,
        dimension INTEGER NOT NULL,
        x INTEGER NOT NULL,
        y INTEGER NOT NULL,
        z INTEGER NOT NULL,
        envelope_data BYTEA NOT NULL,
        envelope_encoding INTEGER NOT NULL,
        source_mutation_id BIGINT NULL,
        rollback_outcome INTEGER NULL,
        failure_code TEXT NULL,
        operator_player_id BIGINT NULL,
        CONSTRAINT fk_blockmutationlogs_player FOREIGN KEY (player_id) REFERENCES players(id) ON UPDATE NO ACTION ON DELETE RESTRICT,
        CONSTRAINT fk_blockmutationlogs_operator FOREIGN KEY (operator_player_id) REFERENCES players(id) ON UPDATE NO ACTION ON DELETE RESTRICT,
        CONSTRAINT fk_blockmutationlogs_source FOREIGN KEY (source_mutation_id) REFERENCES blockmutationlogs(id) ON UPDATE NO ACTION ON DELETE RESTRICT,
        CONSTRAINT ck_blockmutationlogs_timestamp CHECK (timestamp_utc >= 0),
        CONSTRAINT ck_blockmutationlogs_entry_kind CHECK (entry_kind IN (0, 1)),
        CONSTRAINT ck_blockmutationlogs_action_kind CHECK (action_kind IN (1, 2, 3, 4, 5)),
        CONSTRAINT ck_blockmutationlogs_envelope_encoding CHECK (envelope_encoding = 1),
        CONSTRAINT ck_blockmutationlogs_envelope_data_length CHECK (octet_length(envelope_data) <= {BlockStateEnvelope.MaximumEncodedBytes}),
        CONSTRAINT ck_blockmutationlogs_rollback_outcome CHECK (rollback_outcome IS NULL OR rollback_outcome IN (1, 2, 3)),
        CONSTRAINT ck_blockmutationlogs_failure_code_length CHECK (failure_code IS NULL OR (length(failure_code) BETWEEN 1 AND 128 AND btrim(failure_code) <> '')),
        CONSTRAINT ck_blockmutationlogs_failure_code_format CHECK (failure_code IS NULL OR failure_code ~ '^[a-z0-9][a-z0-9._-]{{0,127}}$'),
        CONSTRAINT ck_blockmutationlogs_entry_action_pair CHECK (
            (entry_kind = 0 AND action_kind IN (1, 2, 3, 4))
            OR (entry_kind = 1 AND action_kind = 5)
        ),
        CONSTRAINT ck_blockmutationlogs_rollback_fields CHECK (
            (entry_kind = 0 AND source_mutation_id IS NULL AND rollback_outcome IS NULL AND failure_code IS NULL AND operator_player_id IS NULL)
            OR (entry_kind = 1 AND source_mutation_id IS NOT NULL AND rollback_outcome IS NOT NULL AND operator_player_id IS NOT NULL)
        ),
        CONSTRAINT ck_blockmutationlogs_outcome_failure_pair CHECK (
            rollback_outcome IS NULL
            OR (rollback_outcome = 1 AND failure_code IS NULL)
            OR (rollback_outcome IN (2, 3) AND failure_code IS NOT NULL)
        ),
        CONSTRAINT ck_blockmutationlogs_source_precedes CHECK (source_mutation_id IS NULL OR source_mutation_id < id)
    )";
    private static readonly string EnsureBlockMutationEnvelopeLengthConstraint = $@"DO $migration$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns column_row
            WHERE column_row.table_schema = current_schema()
              AND column_row.table_name = 'blockmutationlogs'
              AND column_row.column_name = 'envelope_data'
              AND column_row.data_type = 'bytea'
        ) AND NOT EXISTS (
            SELECT 1
            FROM pg_catalog.pg_constraint constraint_row
            JOIN pg_catalog.pg_class table_row ON table_row.oid = constraint_row.conrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
            WHERE schema_row.nspname = current_schema()
              AND table_row.relname = 'blockmutationlogs'
              AND constraint_row.conname = 'ck_blockmutationlogs_envelope_data_length'
        ) THEN
            ALTER TABLE blockmutationlogs
                ADD CONSTRAINT ck_blockmutationlogs_envelope_data_length
                CHECK (octet_length(envelope_data) <= {BlockStateEnvelope.MaximumEncodedBytes});
        END IF;
    END
    $migration$;";

    internal const string RollbackBreaksQuery = @"SELECT timestamp_utc, block, x, y, z FROM blocklogs
            WHERE player_id = @playerid
            AND actiontype = 0
            AND x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius";

    internal const string EntityLogByEntityIdQuery = @"SELECT e.id, e.timestamp_utc, p.last_playername, p.playeruid, e.actiontype, e.entityname, e.entityid, e.itemstack_data, e.itemstack_encoding, e.x, e.y, e.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z FROM entitylogs
            WHERE entityid = @entityid
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) e
            LEFT JOIN players p ON e.player_id = p.id
            ORDER BY e.id ASC";

    internal const string LastEntityCoordsQuery = @"SELECT x, y, z
            FROM entitylogs
            WHERE entityid = @entityid
            ORDER BY id DESC
            LIMIT 1";

    internal const string ContainerLogQuery = @"SELECT c.id, c.timestamp_utc, p.last_playername, p.playeruid, c.containerid, c.itemstack_data, c.itemstack_encoding, c.quantity, c.actiontype
                FROM (
                    SELECT id, timestamp_utc, player_id, containerid, itemstack_data, itemstack_encoding, quantity, actiontype
                    FROM containerlogs
                    WHERE containerid = ANY(@containerids)
                    ORDER BY id DESC
                    LIMIT @loglimit OFFSET @skiplognum
                ) c
                LEFT JOIN players p ON c.player_id = p.id
                ORDER BY c.id ASC";

    private static readonly Dictionary<string, Dictionary<string, string>> RequiredColumnTypes = new() {
        ["players"] = new() { ["id"] = "bigint", ["playeruid"] = "text", ["last_playername"] = "text" },
        ["blocklogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["actiontype"] = "integer", ["block"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["x"] = "integer", ["y"] = "integer", ["z"] = "integer", ["oldblockid"] = "integer" },
        ["entitylogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["actiontype"] = "integer", ["entityname"] = "text", ["entityid"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["x"] = "integer", ["y"] = "integer", ["z"] = "integer" },
        ["containerlogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["containerid"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["quantity"] = "integer", ["actiontype"] = "integer" },
        ["blockmutationlogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["entry_kind"] = "integer", ["action_kind"] = "integer", ["dimension"] = "integer", ["x"] = "integer", ["y"] = "integer", ["z"] = "integer", ["envelope_data"] = "bytea", ["envelope_encoding"] = "integer", ["source_mutation_id"] = "bigint", ["rollback_outcome"] = "integer", ["failure_code"] = "text", ["operator_player_id"] = "bigint" }
    };
    private static readonly Dictionary<string, bool> BlockMutationColumnNullability = new() {
        ["id"] = false,
        ["timestamp_utc"] = false,
        ["player_id"] = true,
        ["entry_kind"] = false,
        ["action_kind"] = false,
        ["dimension"] = false,
        ["x"] = false,
        ["y"] = false,
        ["z"] = false,
        ["envelope_data"] = false,
        ["envelope_encoding"] = false,
        ["source_mutation_id"] = true,
        ["rollback_outcome"] = true,
        ["failure_code"] = true,
        ["operator_player_id"] = true
    };
    private static readonly Dictionary<string, string> RequiredBlockMutationChecks = new() {
        ["ck_blockmutationlogs_timestamp"] = "CHECK ((timestamp_utc >= 0))",
        ["ck_blockmutationlogs_entry_kind"] = "CHECK ((entry_kind = ANY (ARRAY[0, 1])))",
        ["ck_blockmutationlogs_action_kind"] = "CHECK ((action_kind = ANY (ARRAY[1, 2, 3, 4, 5])))",
        ["ck_blockmutationlogs_envelope_encoding"] = "CHECK ((envelope_encoding = 1))",
        ["ck_blockmutationlogs_envelope_data_length"] = $"CHECK ((octet_length(envelope_data) <= {BlockStateEnvelope.MaximumEncodedBytes}))",
        ["ck_blockmutationlogs_rollback_outcome"] = "CHECK (((rollback_outcome IS NULL) OR (rollback_outcome = ANY (ARRAY[1, 2, 3]))))",
        ["ck_blockmutationlogs_failure_code_length"] = "CHECK (((failure_code IS NULL) OR (((length(failure_code) >= 1) AND (length(failure_code) <= 128)) AND (btrim(failure_code) <> ''::text))))",
        ["ck_blockmutationlogs_failure_code_format"] = "CHECK (((failure_code IS NULL) OR (failure_code ~ '^[a-z0-9][a-z0-9._-]{0,127}$'::text)))",
        ["ck_blockmutationlogs_entry_action_pair"] = "CHECK ((((entry_kind = 0) AND (action_kind = ANY (ARRAY[1, 2, 3, 4]))) OR ((entry_kind = 1) AND (action_kind = 5))))",
        ["ck_blockmutationlogs_rollback_fields"] = "CHECK ((((entry_kind = 0) AND (source_mutation_id IS NULL) AND (rollback_outcome IS NULL) AND (failure_code IS NULL) AND (operator_player_id IS NULL)) OR ((entry_kind = 1) AND (source_mutation_id IS NOT NULL) AND (rollback_outcome IS NOT NULL) AND (operator_player_id IS NOT NULL))))",
        ["ck_blockmutationlogs_outcome_failure_pair"] = "CHECK (((rollback_outcome IS NULL) OR ((rollback_outcome = 1) AND (failure_code IS NULL)) OR ((rollback_outcome = ANY (ARRAY[2, 3])) AND (failure_code IS NOT NULL))))",
        ["ck_blockmutationlogs_source_precedes"] = "CHECK (((source_mutation_id IS NULL) OR (source_mutation_id < id)))"
    };

    public enum ActionType {
        BROKE = 0,
        PLACED = 1,
        USED = 2,
        INTERACTED = 3,
        KILLED = 4,
        TAKEN = 5,
        SWAP = 6,
        SAME_ITEM = 7,
        SPAWNED = 8,
        DESPAWNED = 9
    }

    private static readonly Dictionary<string, int> ActionTypeMap = new Dictionary<string, int> {
        { "BROKE", (int)ActionType.BROKE },
        { "PLACED", (int)ActionType.PLACED },
        { "USED", (int)ActionType.USED },
        { "INTERACTED", (int)ActionType.INTERACTED },
        { "KILLED", (int)ActionType.KILLED },
        { "TAKEN", (int)ActionType.TAKEN },
        { "SWAP", (int)ActionType.SWAP },
        { "SAME_ITEM", (int)ActionType.SAME_ITEM },
        { "SPAWNED", (int)ActionType.SPAWNED },
        { "DESPAWNED", (int)ActionType.DESPAWNED }
    };

    private static readonly Dictionary<int, string> ReverseActionTypeMap = new Dictionary<int, string> {
        { (int)ActionType.BROKE, "BROKE" },
        { (int)ActionType.PLACED, "PLACED" },
        { (int)ActionType.USED, "USED" },
        { (int)ActionType.INTERACTED, "INTERACTED" },
        { (int)ActionType.KILLED, "KILLED" },
        { (int)ActionType.TAKEN, "TAKEN" },
        { (int)ActionType.SWAP, "SWAP" },
        { (int)ActionType.SAME_ITEM, "SAME_ITEM" },
        { (int)ActionType.SPAWNED, "SPAWNED" },
        { (int)ActionType.DESPAWNED, "DESPAWNED" }
    };

    public Database() : this(DefaultWriterQueueCapacity) { }

    internal Database(int writerQueueCapacity) {
        if (writerQueueCapacity <= 0) throw new ArgumentOutOfRangeException(nameof(writerQueueCapacity));
        dataSource = DatabaseConfiguration.CreateDataSource();
        try {
            using (var connection = dataSource.OpenConnection()) {
                using (var versionCmd = connection.CreateCommand()) {
                    versionCmd.CommandText = "SHOW server_version_num;";
                    if (Convert.ToInt32(versionCmd.ExecuteScalar()) < 170000) {
                        throw new InvalidOperationException("GriefLedger requires PostgreSQL 17 or newer.");
                    }
                }

                using var transaction = connection.BeginTransaction();
                using (var cmd = connection.CreateCommand()) {
                    cmd.Transaction = transaction;
                    cmd.CommandText = CreatePlayersTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateBlockLogsTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateEntityLogsTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateContainerLogsTable;
                    cmd.ExecuteNonQuery();
                    // Additive migration for installations bootstrapped with the original four tables.
                    cmd.CommandText = CreateBlockMutationLogsTable;
                    cmd.ExecuteNonQuery();
                    // Existing exact-ledger schemas predate the per-row envelope bound. Add it
                    // before shape validation; an incompatible same-name constraint is preserved
                    // here and then rejected by the canonical validator below.
                    cmd.CommandText = EnsureBlockMutationEnvelopeLengthConstraint;
                    cmd.ExecuteNonQuery();

                    ValidateSchema(connection, transaction);

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_coords ON blocklogs(x, y, z);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_coords ON entitylogs(x, y, z);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_id ON containerlogs(containerid);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_entityid_id_desc ON entitylogs(entityid, id DESC);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_containerid_id_desc ON containerlogs(containerid, id DESC);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_ts ON blocklogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_pid_ts ON blocklogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_act_ts ON blocklogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_ts ON entitylogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_pid_ts ON entitylogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_act_ts ON entitylogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_ts ON containerlogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_pid_ts ON containerlogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_act_ts ON containerlogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blockmutationlogs_player_dimension_id_desc ON blockmutationlogs(player_id, dimension, id DESC);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blockmutationlogs_replay_candidates ON blockmutationlogs(player_id, dimension, action_kind, x, y, z, id DESC) WHERE entry_kind = 0;";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blockmutationlogs_dimension_coords_id_desc ON blockmutationlogs(dimension, x, y, z, id DESC);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blockmutationlogs_source_outcome ON blockmutationlogs(source_mutation_id, rollback_outcome);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE UNIQUE INDEX IF NOT EXISTS ux_blockmutationlogs_successful_source ON blockmutationlogs(source_mutation_id) WHERE entry_kind = 1 AND rollback_outcome = 1;";
                    cmd.ExecuteNonQuery();

                    ValidateBlockMutationIndexes(connection, transaction);
                }
                transaction.Commit();
            }
        }
        catch {
            dataSource.Dispose();
            throw;
        }

        databaseTasks = new BlockingCollection<WriterWorkItem>(new ConcurrentQueue<WriterWorkItem>(), writerQueueCapacity);
        workerThread = new Thread(WorkerLoop);
        workerThread.IsBackground = true;
        workerThread.Name = "GriefLedger database writer";
        workerThread.Start();
    }

    private static void ValidateSchema(NpgsqlConnection connection, NpgsqlTransaction transaction) {
        var actualColumns = new Dictionary<string, Dictionary<string, (string Type, bool IsIdentity, bool IsNullable)>>(StringComparer.Ordinal);
        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = @"SELECT table_name, column_name, data_type, is_identity, is_nullable
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ANY(@tables);";
        AddParameter(cmd, "@tables", NpgsqlDbType.Array | NpgsqlDbType.Text, new List<string>(RequiredColumnTypes.Keys).ToArray());
        using (var reader = cmd.ExecuteReader()) {
            while (reader.Read()) {
                string table = reader.GetString(0);
                if (!actualColumns.TryGetValue(table, out var columns)) {
                    columns = new Dictionary<string, (string Type, bool IsIdentity, bool IsNullable)>(StringComparer.Ordinal);
                    actualColumns[table] = columns;
                }
                columns[reader.GetString(1)] = (reader.GetString(2), reader.GetString(3) == "YES", reader.GetString(4) == "YES");
            }
        }

        foreach (var table in RequiredColumnTypes) {
            if (!actualColumns.TryGetValue(table.Key, out var columns)) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: required table " + table.Key + " was not found in the current schema.");
            }
            foreach (var expectedColumn in table.Value) {
                if (!columns.TryGetValue(expectedColumn.Key, out var actual)) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: required column " + table.Key + "." + expectedColumn.Key + " was not found.");
                }
                if (!String.Equals(actual.Type, expectedColumn.Value, StringComparison.Ordinal)) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: " + table.Key + "." + expectedColumn.Key + " must use PostgreSQL type " + expectedColumn.Value + ".");
                }
                if (expectedColumn.Key == "id" && !actual.IsIdentity) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: " + table.Key + ".id must be an identity column.");
                }
                if (table.Key == "blockmutationlogs" && actual.IsNullable != BlockMutationColumnNullability[expectedColumn.Key]) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: blockmutationlogs." + expectedColumn.Key + " has incompatible nullability.");
                }
            }
        }

        foreach (string tableName in RequiredColumnTypes.Keys) {
            cmd.Parameters.Clear();
            cmd.CommandText = @"SELECT EXISTS (
                SELECT 1
                FROM pg_catalog.pg_constraint constraint_row
                JOIN pg_catalog.pg_class table_row ON table_row.oid = constraint_row.conrelid
                JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
                JOIN pg_catalog.pg_attribute id_column
                  ON id_column.attrelid = table_row.oid
                 AND id_column.attname = 'id'
                 AND NOT id_column.attisdropped
                WHERE schema_row.nspname = current_schema()
                  AND table_row.relname = @table_name
                  AND constraint_row.contype = 'p'
                  AND NOT constraint_row.condeferrable
                  AND NOT constraint_row.condeferred
                  AND constraint_row.convalidated
                  AND constraint_row.conkey = ARRAY[id_column.attnum]::smallint[]
            );";
            AddParameter(cmd, "@table_name", NpgsqlDbType.Text, tableName);
            if (!(bool)(cmd.ExecuteScalar() ?? false)) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: " + tableName + ".id must be the sole column of a validated, non-deferrable primary key.");
            }
        }

        cmd.Parameters.Clear();
        cmd.CommandText = @"SELECT EXISTS (
            SELECT 1
            FROM pg_catalog.pg_index index_row
            JOIN pg_catalog.pg_class table_row ON table_row.oid = index_row.indrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
            JOIN pg_catalog.pg_attribute uid_column
              ON uid_column.attrelid = table_row.oid
             AND uid_column.attname = 'playeruid'
             AND NOT uid_column.attisdropped
            WHERE schema_row.nspname = current_schema()
              AND table_row.relname = 'players'
              AND index_row.indisunique
              AND index_row.indimmediate
              AND index_row.indisvalid
              AND index_row.indisready
              AND index_row.indpred IS NULL
              AND index_row.indexprs IS NULL
              AND index_row.indnkeyatts = 1
              AND index_row.indkey[0] = uid_column.attnum
        );";
        if (!(bool)(cmd.ExecuteScalar() ?? false)) {
            throw new InvalidOperationException("GriefLedger database schema validation failed: players.playeruid must have a valid, immediate, non-partial single-column unique index usable by ON CONFLICT.");
        }

        ValidateBlockMutationForeignKeys(connection, transaction);
        ValidateBlockMutationChecks(connection, transaction);
    }

    private static void ValidateBlockMutationForeignKeys(NpgsqlConnection connection, NpgsqlTransaction transaction) {
        var expected = new Dictionary<string, (string Column, string ReferencedTable)>(StringComparer.Ordinal) {
            ["fk_blockmutationlogs_player"] = ("player_id", "players"),
            ["fk_blockmutationlogs_operator"] = ("operator_player_id", "players"),
            ["fk_blockmutationlogs_source"] = ("source_mutation_id", "blockmutationlogs")
        };
        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = @"SELECT constraint_row.conname,
                local_column.attname, referenced_schema.nspname = current_schema(), referenced_table.relname, referenced_column.attname,
                constraint_row.confupdtype::text, constraint_row.confdeltype::text,
                constraint_row.confmatchtype::text, constraint_row.convalidated,
                constraint_row.condeferrable, constraint_row.condeferred,
                cardinality(constraint_row.conkey), cardinality(constraint_row.confkey)
            FROM pg_catalog.pg_constraint constraint_row
            JOIN pg_catalog.pg_class local_table ON local_table.oid = constraint_row.conrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = local_table.relnamespace
            JOIN pg_catalog.pg_class referenced_table ON referenced_table.oid = constraint_row.confrelid
            JOIN pg_catalog.pg_namespace referenced_schema ON referenced_schema.oid = referenced_table.relnamespace
            JOIN pg_catalog.pg_attribute local_column
              ON local_column.attrelid = local_table.oid AND local_column.attnum = constraint_row.conkey[1]
            JOIN pg_catalog.pg_attribute referenced_column
              ON referenced_column.attrelid = referenced_table.oid AND referenced_column.attnum = constraint_row.confkey[1]
            WHERE schema_row.nspname = current_schema()
              AND local_table.relname = 'blockmutationlogs'
              AND constraint_row.contype = 'f';";
        var actualNames = new HashSet<string>(StringComparer.Ordinal);
        using var reader = cmd.ExecuteReader();
        while (reader.Read()) {
            string name = reader.GetString(0);
            actualNames.Add(name);
            if (!expected.TryGetValue(name, out var shape)
                || reader.GetString(1) != shape.Column
                || !reader.GetBoolean(2)
                || reader.GetString(3) != shape.ReferencedTable
                || reader.GetString(4) != "id"
                || reader.GetString(5) != "a"
                || reader.GetString(6) != "r"
                || reader.GetString(7) != "s"
                || !reader.GetBoolean(8)
                || reader.GetBoolean(9)
                || reader.GetBoolean(10)
                || reader.GetInt32(11) != 1
                || reader.GetInt32(12) != 1) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: foreign key " + name + " has an incompatible definition.");
            }
        }
        foreach (string name in expected.Keys) {
            if (!actualNames.Contains(name)) throw new InvalidOperationException("GriefLedger database schema validation failed: required foreign key " + name + " was not found.");
        }
    }

    private static void ValidateBlockMutationChecks(NpgsqlConnection connection, NpgsqlTransaction transaction) {
        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = @"SELECT constraint_row.conname, pg_catalog.pg_get_constraintdef(constraint_row.oid, false),
                constraint_row.convalidated, constraint_row.condeferrable, constraint_row.condeferred
            FROM pg_catalog.pg_constraint constraint_row
            JOIN pg_catalog.pg_class table_row ON table_row.oid = constraint_row.conrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
            WHERE schema_row.nspname = current_schema()
              AND table_row.relname = 'blockmutationlogs'
              AND constraint_row.contype = 'c';";
        var actualNames = new HashSet<string>(StringComparer.Ordinal);
        using var reader = cmd.ExecuteReader();
        while (reader.Read()) {
            string name = reader.GetString(0);
            if (!RequiredBlockMutationChecks.TryGetValue(name, out string? expectedDefinition)) continue;
            actualNames.Add(name);
            if (NormalizeSql(reader.GetString(1)) != NormalizeSql(expectedDefinition)
                || !reader.GetBoolean(2) || reader.GetBoolean(3) || reader.GetBoolean(4)) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: check constraint " + name + " has an incompatible definition.");
            }
        }
        foreach (string name in RequiredBlockMutationChecks.Keys) {
            if (!actualNames.Contains(name)) throw new InvalidOperationException("GriefLedger database schema validation failed: required check constraint " + name + " was not found.");
        }
    }

    private static void ValidateBlockMutationIndexes(NpgsqlConnection connection, NpgsqlTransaction transaction) {
        ValidateBlockMutationIndex(connection, transaction, "idx_blockmutationlogs_player_dimension_id_desc", ["player_id", "dimension", "id"], [0, 0, 3], false, null);
        ValidateBlockMutationIndex(connection, transaction, "idx_blockmutationlogs_replay_candidates", ["player_id", "dimension", "action_kind", "x", "y", "z", "id"], [0, 0, 0, 0, 0, 0, 3], false, "(entry_kind = 0)");
        ValidateBlockMutationIndex(connection, transaction, "idx_blockmutationlogs_dimension_coords_id_desc", ["dimension", "x", "y", "z", "id"], [0, 0, 0, 0, 3], false, null);
        ValidateBlockMutationIndex(connection, transaction, "idx_blockmutationlogs_source_outcome", ["source_mutation_id", "rollback_outcome"], [0, 0], false, null);
        ValidateBlockMutationIndex(connection, transaction, "ux_blockmutationlogs_successful_source", ["source_mutation_id"], [0], true, "((entry_kind = 1) AND (rollback_outcome = 1))");
    }

    private static void ValidateBlockMutationIndex(NpgsqlConnection connection, NpgsqlTransaction transaction,
        string indexName, string[] expectedKeys, short[] expectedOptions, bool expectedUnique, string? expectedPredicate,
        bool expectedNullsNotDistinct = false) {
        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = @"SELECT index_row.indisunique, index_row.indisvalid, index_row.indisready,
                index_row.indimmediate, index_row.indnullsnotdistinct, index_row.indnkeyatts, index_row.indnatts,
                index_row.indexprs IS NULL, access_method.amname,
                pg_catalog.pg_get_expr(index_row.indpred, index_row.indrelid, false),
                ARRAY(SELECT pg_catalog.pg_get_indexdef(index_row.indexrelid, key_number, false)
                      FROM generate_series(1, index_row.indnkeyatts) key_number ORDER BY key_number),
                index_row.indoption::smallint[]
            FROM pg_catalog.pg_index index_row
            JOIN pg_catalog.pg_class index_table ON index_table.oid = index_row.indexrelid
            JOIN pg_catalog.pg_class data_table ON data_table.oid = index_row.indrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = data_table.relnamespace
            JOIN pg_catalog.pg_am access_method ON access_method.oid = index_table.relam
            WHERE schema_row.nspname = current_schema()
              AND data_table.relname = 'blockmutationlogs'
              AND index_table.relname = @index_name;";
        AddParameter(cmd, "@index_name", NpgsqlDbType.Text, indexName);
        using var reader = cmd.ExecuteReader();
        if (!reader.Read()) throw new InvalidOperationException("GriefLedger database schema validation failed: required index " + indexName + " was not found.");
        string? actualPredicate = reader.IsDBNull(9) ? null : reader.GetString(9);
        string[] actualKeys = reader.GetFieldValue<string[]>(10);
        short[] actualOptions = reader.GetFieldValue<short[]>(11);
        if (reader.GetBoolean(0) != expectedUnique || !reader.GetBoolean(1) || !reader.GetBoolean(2)
            || !reader.GetBoolean(3) || reader.GetBoolean(4) != expectedNullsNotDistinct
            || reader.GetInt16(5) != expectedKeys.Length || reader.GetInt16(6) != expectedKeys.Length
            || !reader.GetBoolean(7) || reader.GetString(8) != "btree"
            || !actualKeys.AsSpan().SequenceEqual(expectedKeys)
            || !actualOptions.AsSpan().SequenceEqual(expectedOptions)
            || (actualPredicate == null) != (expectedPredicate == null)
            || (actualPredicate != null && NormalizeSql(actualPredicate) != NormalizeSql(expectedPredicate!))) {
            throw new InvalidOperationException("GriefLedger database schema validation failed: index " + indexName + " has an incompatible definition.");
        }
        if (reader.Read()) throw new InvalidOperationException("GriefLedger database schema validation failed: index " + indexName + " is ambiguous.");
    }

    private static string NormalizeSql(string value) {
        var builder = new System.Text.StringBuilder(value.Length);
        int index = 0;
        while (index < value.Length) {
            char character = value[index];
            if (character is '\'' or '"') {
                char quote = character;
                builder.Append(character);
                index++;
                while (index < value.Length) {
                    character = value[index];
                    builder.Append(character);
                    index++;
                    if (character != quote) continue;
                    if (index < value.Length && value[index] == quote) {
                        builder.Append(value[index]);
                        index++;
                        continue;
                    }
                    break;
                }
                continue;
            }
            if (character == '$' && TryReadDollarQuoteDelimiter(value, index, out string delimiter)) {
                builder.Append(delimiter);
                index += delimiter.Length;
                int closing = value.IndexOf(delimiter, index, StringComparison.Ordinal);
                if (closing < 0) {
                    builder.Append(value, index, value.Length - index);
                    break;
                }
                builder.Append(value, index, closing - index + delimiter.Length);
                index = closing + delimiter.Length;
                continue;
            }
            if (!char.IsWhiteSpace(character)) builder.Append(character);
            index++;
        }
        return builder.ToString();
    }

    private static bool TryReadDollarQuoteDelimiter(string value, int offset, out string delimiter) {
        int index = offset + 1;
        if (index < value.Length && value[index] == '$') {
            delimiter = "$$";
            return true;
        }
        if (index >= value.Length || !(value[index] == '_' || char.IsAsciiLetter(value[index]))) {
            delimiter = string.Empty;
            return false;
        }
        index++;
        while (index < value.Length && (value[index] == '_' || char.IsAsciiLetterOrDigit(value[index]))) index++;
        if (index >= value.Length || value[index] != '$') {
            delimiter = string.Empty;
            return false;
        }
        delimiter = value.Substring(offset, index - offset + 1);
        return true;
    }

    private void WorkerLoop() {
        foreach (WriterWorkItem task in databaseTasks.GetConsumingEnumerable()) {
            Interlocked.Increment(ref activeWriterWorkCount);
            try {
                Exception? writerFailure = Volatile.Read(ref terminalWriterFailure);
                if (writerFailure != null) {
                    task.Fail?.Invoke(new DatabaseWriterUnavailableException(writerFailure));
                    continue;
                }
                try {
                    using (var connection = dataSource.OpenConnection()) {
                        task.Execute(connection);
                    }
                    task.Complete?.Invoke();
                }
                catch (Exception ex) {
                    Interlocked.CompareExchange(ref terminalWriterFailure, ex, null);
                    task.Fail?.Invoke(ex);
                    // Awaited writes have an observer/caller which owns the single contextual error
                    // report. Only fire-and-forget writes need the worker to report the first failure.
                    if (task.Fail == null) {
                        LogError("GriefLedger: A queued database write failed and was not retried: " + ex);
                    }
                }
            }
            finally {
                Interlocked.Decrement(ref activeWriterWorkCount);
            }
        }
    }

    private static void LogError(string message) {
        Main.API?.Logger.Error(message);
    }

    private void QueueWrite(Action<NpgsqlConnection> task) {
        bool rejected = false;
        lock (lifecycleLock) {
            if (!acceptingWrites) {
                LogError("GriefLedger: Rejected a database write because the database is shutting down.");
                return;
            }
            if (Volatile.Read(ref terminalWriterFailure) != null) {
                Interlocked.Increment(ref rejectedWriterWorkCount);
                return;
            }
            if (!databaseTasks.TryAdd(new WriterWorkItem { Execute = task })) rejected = true;
        }
        if (rejected) ReportWriterQueueFull();
    }

    private Task<long> QueueResultWrite(Action<NpgsqlConnection, Action<long>> execute, bool isBarrier) {
        var completion = new TaskCompletionSource<long>(TaskCreationOptions.RunContinuationsAsynchronously);
        long result = 0;
        bool queueFull = false;
        lock (lifecycleLock) {
            if (!acceptingWrites) {
                completion.SetException(new ObjectDisposedException(nameof(Database), "The database writer is shutting down."));
                return completion.Task;
            }
            Exception? writerFailure = Volatile.Read(ref terminalWriterFailure);
            if (writerFailure != null) {
                Interlocked.Increment(ref rejectedWriterWorkCount);
                completion.SetException(new DatabaseWriterUnavailableException(writerFailure));
                return completion.Task;
            }
            if (!databaseTasks.TryAdd(new WriterWorkItem {
                Execute = connection => execute(connection, value => result = value),
                Complete = () => completion.TrySetResult(result),
                Fail = exception => completion.TrySetException(exception),
                IsBarrier = isBarrier
            })) {
                queueFull = true;
                completion.TrySetException(new DatabaseWriterQueueFullException(databaseTasks.BoundedCapacity));
            }
        }
        if (queueFull) ReportWriterQueueFull();
        return completion.Task;
    }

    internal int PendingWriterWorkCount => databaseTasks.Count;
    internal int ActiveWriterWorkCount => Volatile.Read(ref activeWriterWorkCount);
    internal long RejectedWriterWorkCount => Interlocked.Read(ref rejectedWriterWorkCount);

    private void ReportWriterQueueFull() {
        Interlocked.Increment(ref rejectedWriterWorkCount);
        long now = Environment.TickCount64;
        long prior = Interlocked.Read(ref lastQueueFullLogTicks);
        if (now - prior >= 10_000 && Interlocked.CompareExchange(ref lastQueueFullLogTicks, now, prior) == prior) {
            LogError("GriefLedger: Database writer queue is full; work was rejected to protect the game thread and bound retained memory.");
        }
    }

    private bool TryBeginRead(string operation) {
        lock (lifecycleLock) {
            if (!acceptingReads) {
                LogError("GriefLedger: Rejected database read '" + operation + "' because the database is shutting down.");
                return false;
            }
            activeReads++;
            readsDrained.Reset();
            return true;
        }
    }

    private void EndRead() {
        lock (lifecycleLock) {
            activeReads--;
            if (activeReads == 0) readsDrained.Set();
        }
    }

    private void QueueRead(string operation, Action read) {
        if (!TryBeginRead(operation)) return;

        try {
            Task.Run(() => {
                try {
                    read();
                }
                catch (Exception ex) {
                    LogError("GriefLedger: Database read '" + operation + "' failed: " + ex);
                }
                finally {
                    EndRead();
                }
            });
        }
        catch (Exception ex) {
            EndRead();
            LogError("GriefLedger: Database read '" + operation + "' could not be scheduled: " + ex);
        }
    }

    private Task<T> QueueReadAsync<T>(string operation, System.Func<NpgsqlConnection, CancellationToken, Task<T>> read,
        CancellationToken cancellationToken) {
        ArgumentNullException.ThrowIfNull(read);
        if (!TryBeginRead(operation)) {
            return Task.FromException<T>(new ObjectDisposedException(nameof(Database), "The database is shutting down."));
        }

        try {
            return Task.Run(async () => {
                try {
                    cancellationToken.ThrowIfCancellationRequested();
                    await using NpgsqlConnection connection = await dataSource.OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
                    return await read(connection, cancellationToken).ConfigureAwait(false);
                }
                finally {
                    EndRead();
                }
            }, CancellationToken.None);
        }
        catch (Exception exception) {
            EndRead();
            return Task.FromException<T>(exception);
        }
    }

    private static void AddParameter(NpgsqlCommand cmd, string name, NpgsqlDbType type, object? value) {
        cmd.Parameters.Add(new NpgsqlParameter(name, type) { Value = value ?? DBNull.Value });
    }

    public (byte[]? data, int encoding) CompressText(string? value) {
        if (value == null) return (null, 0);

        byte[] utf8Bytes = System.Text.Encoding.UTF8.GetBytes(value);
        using var outputStream = new MemoryStream();
        using (var brotliStream = new System.IO.Compression.BrotliStream(outputStream, System.IO.Compression.CompressionLevel.Optimal)) {
            brotliStream.Write(utf8Bytes, 0, utf8Bytes.Length);
        }

        byte[] compressedBytes = outputStream.ToArray();
        if (compressedBytes.Length < utf8Bytes.Length) {
            return (compressedBytes, 2);
        }
        return (utf8Bytes, 1);
    }

    public string? DecompressText(byte[]? data, int encoding) {
        if (data == null || encoding == 0) return null;
        if (encoding == 1) return System.Text.Encoding.UTF8.GetString(data);
        if (encoding == 2) {
            using var inputStream = new MemoryStream(data);
            using var brotliStream = new System.IO.Compression.BrotliStream(inputStream, System.IO.Compression.CompressionMode.Decompress);
            using var outputStream = new MemoryStream();
            brotliStream.CopyTo(outputStream);
            return System.Text.Encoding.UTF8.GetString(outputStream.ToArray());
        }
        return null;
    }

    private long GetOrInsertPlayer(NpgsqlConnection connection, string? playername, string? playeruid, NpgsqlTransaction? transaction = null) {
        if (playername == null && playeruid == null) return -1;

        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        if (playeruid != null) {
            cmd.CommandText = @"INSERT INTO players (playeruid, last_playername)
                VALUES (@uid, @name)
                ON CONFLICT (playeruid) DO UPDATE
                SET last_playername = EXCLUDED.last_playername
                RETURNING id;";
            AddParameter(cmd, "@uid", NpgsqlDbType.Text, playeruid);
            AddParameter(cmd, "@name", NpgsqlDbType.Text, playername);
            return Convert.ToInt64(cmd.ExecuteScalar());
        }
        else {
            cmd.CommandText = "INSERT INTO players (last_playername) VALUES (@name) RETURNING id;";
            AddParameter(cmd, "@name", NpgsqlDbType.Text, playername);
            return Convert.ToInt64(cmd.ExecuteScalar());
        }
    }

    /// <summary>Queues an immutable append on the same FIFO writer used by the legacy logs.</summary>
    public Task<long> EnqueueBlockMutationAppend(BlockMutationAppend append) {
        ArgumentNullException.ThrowIfNull(append);
        byte[] envelope = append.CopyEnvelopeData();
        return QueueResultWrite((connection, setResult) => {
            using NpgsqlTransaction transaction = connection.BeginTransaction();
            if (append.EntryKind == BlockMutationEntryKind.Rollback) {
                using var sourceCmd = connection.CreateCommand();
                sourceCmd.Transaction = transaction;
                sourceCmd.CommandText = @"SELECT entry_kind, action_kind, dimension, x, y, z,
                        envelope_data, envelope_encoding
                    FROM blockmutationlogs
                    WHERE id = @source_mutation_id
                    FOR SHARE;";
                AddParameter(sourceCmd, "@source_mutation_id", NpgsqlDbType.Bigint, append.SourceMutationId);
                using (var sourceReader = sourceCmd.ExecuteReader()) {
                    if (!sourceReader.Read()) throw new InvalidOperationException("The rollback source mutation does not exist or is not committed.");
                    if (sourceReader.GetInt32(0) != (int)BlockMutationEntryKind.Mutation) {
                        throw new InvalidOperationException("A rollback source must be a mutation entry.");
                    }
                    BlockMutationActionKind sourceAction = (BlockMutationActionKind)sourceReader.GetInt32(1);
                    if (!Enum.IsDefined(sourceAction) || sourceAction is BlockMutationActionKind.Unknown or BlockMutationActionKind.Rollback) {
                        throw new InvalidOperationException("A rollback source must use a supported mutation action.");
                    }
                    if (sourceReader.GetInt32(2) != append.Dimension || sourceReader.GetInt32(3) != append.X
                        || sourceReader.GetInt32(4) != append.Y || sourceReader.GetInt32(5) != append.Z) {
                        throw new InvalidOperationException("A rollback entry must use the source mutation's dimension and absolute coordinates.");
                    }
                    int sourceEncoding = sourceReader.GetInt32(7);
                    if (sourceEncoding != BlockStateEnvelope.BinaryEncoding) {
                        throw new InvalidOperationException("The rollback source uses an unsupported envelope encoding.");
                    }
                    BlockStateEnvelope sourceEnvelope = BlockStateEnvelope.Decode(sourceReader.GetFieldValue<byte[]>(6));
                    var exactInverse = new BlockStateEnvelope(sourceEnvelope.After, sourceEnvelope.Before);
                    byte[] expectedInverseBytes = exactInverse.Encode();
                    if (!append.DecodeEnvelope().Equals(exactInverse)
                        || !envelope.AsSpan().SequenceEqual(expectedInverseBytes)) {
                        throw new InvalidOperationException("A rollback entry must store the exact inverse of its source mutation envelope.");
                    }
                }
            }
            long actorPlayerId = GetOrInsertPlayer(connection, append.ActorPlayerName, append.ActorPlayerUid, transaction);
            long operatorPlayerId = GetOrInsertPlayer(connection, append.OperatorPlayerName, append.OperatorPlayerUid, transaction);
            using var cmd = connection.CreateCommand();
            cmd.Transaction = transaction;
            cmd.CommandText = @"INSERT INTO blockmutationlogs
                (timestamp_utc, player_id, entry_kind, action_kind, dimension, x, y, z,
                 envelope_data, envelope_encoding, source_mutation_id, rollback_outcome,
                 failure_code, operator_player_id)
                VALUES
                (@timestamp_utc, @player_id, @entry_kind, @action_kind, @dimension, @x, @y, @z,
                 @envelope_data, @envelope_encoding, @source_mutation_id, @rollback_outcome,
                 @failure_code, @operator_player_id)
                RETURNING id;";
            AddParameter(cmd, "@timestamp_utc", NpgsqlDbType.Bigint, append.TimestampUtc);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, actorPlayerId == -1 ? null : actorPlayerId);
            AddParameter(cmd, "@entry_kind", NpgsqlDbType.Integer, (int)append.EntryKind);
            AddParameter(cmd, "@action_kind", NpgsqlDbType.Integer, (int)append.ActionKind);
            AddParameter(cmd, "@dimension", NpgsqlDbType.Integer, append.Dimension);
            AddParameter(cmd, "@x", NpgsqlDbType.Integer, append.X);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, append.Y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, append.Z);
            AddParameter(cmd, "@envelope_data", NpgsqlDbType.Bytea, envelope);
            AddParameter(cmd, "@envelope_encoding", NpgsqlDbType.Integer, append.EnvelopeEncoding);
            AddParameter(cmd, "@source_mutation_id", NpgsqlDbType.Bigint, append.SourceMutationId);
            AddParameter(cmd, "@rollback_outcome", NpgsqlDbType.Integer, append.RollbackOutcome.HasValue ? (int)append.RollbackOutcome.Value : null);
            AddParameter(cmd, "@failure_code", NpgsqlDbType.Text, append.FailureCode);
            AddParameter(cmd, "@operator_player_id", NpgsqlDbType.Bigint, operatorPlayerId == -1 ? null : operatorPlayerId);
            long id = Convert.ToInt64(cmd.ExecuteScalar());
            transaction.Commit();
            setResult(id);
        }, false);
    }

    public Task<long> EnqueueBlockMutationAppendAsync(BlockMutationAppend append) => EnqueueBlockMutationAppend(append);

    /// <summary>
    /// Enqueues a FIFO barrier and returns the durable maximum ledger id after every earlier
    /// queued write has completed. Any earlier writer failure is surfaced instead of returning
    /// a potentially misleading cutoff.
    /// </summary>
    public Task<long> GetDurableBlockMutationCutoffAsync() {
        return QueueResultWrite((connection, setResult) => {
            using NpgsqlTransaction transaction = connection.BeginTransaction();
            using var cmd = connection.CreateCommand();
            cmd.Transaction = transaction;
            // SHARE conflicts with the ROW EXCLUSIVE lock used by INSERT/UPDATE/DELETE. This
            // waits for existing direct writers and excludes new ones until MAX(id) is read and
            // committed, making the result a stable durable prefix for normal identity inserts.
            cmd.CommandText = @"LOCK TABLE blockmutationlogs IN SHARE MODE;
                SELECT COALESCE(MAX(id), 0) FROM blockmutationlogs;";
            long cutoff = Convert.ToInt64(cmd.ExecuteScalar());
            transaction.Commit();
            setResult(cutoff);
        }, true);
    }

    public Task<long> GetDurableMutationCutoffAsync() => GetDurableBlockMutationCutoffAsync();

    /// <summary>Resolves an immutable UID exactly. World/player APIs are never touched by this read.</summary>
    public Task<BlockMutationPlayer?> ResolveBlockMutationPlayerByUidAsync(string playerUid,
        CancellationToken cancellationToken = default) {
        if (string.IsNullOrWhiteSpace(playerUid)) throw new ArgumentException("A nonempty immutable player UID is required.", nameof(playerUid));
        return QueueReadAsync("resolve exact-ledger player UID", async (connection, token) => {
            await using NpgsqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, playeruid, last_playername
                FROM players
                WHERE playeruid = @player_uid
                ORDER BY id
                LIMIT 2;";
            AddParameter(cmd, "@player_uid", NpgsqlDbType.Text, playerUid);
            await using NpgsqlDataReader reader = await cmd.ExecuteReaderAsync(token).ConfigureAwait(false);
            BlockMutationPlayer? player = null;
            if (await reader.ReadAsync(token).ConfigureAwait(false)) {
                player = ReadPlayer(reader);
            }
            if (await reader.ReadAsync(token).ConfigureAwait(false)) {
                throw new InvalidOperationException("The immutable player UID is not unique in the players table.");
            }
            return player;
        }, cancellationToken);
    }

    /// <summary>Resolves a case-insensitive last-known name only when it identifies one player row.</summary>
    public Task<BlockMutationPlayerNameResolution> ResolveBlockMutationPlayerByNameAsync(string playerName,
        CancellationToken cancellationToken = default) {
        if (string.IsNullOrWhiteSpace(playerName)) throw new ArgumentException("A nonempty player name is required.", nameof(playerName));
        return QueueReadAsync("resolve exact-ledger player name", async (connection, token) => {
            await using NpgsqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT id, playeruid, last_playername
                FROM players
                WHERE lower(last_playername) = lower(@player_name)
                ORDER BY id
                LIMIT 2;";
            AddParameter(cmd, "@player_name", NpgsqlDbType.Text, playerName);
            var players = new List<BlockMutationPlayer>();
            await using NpgsqlDataReader reader = await cmd.ExecuteReaderAsync(token).ConfigureAwait(false);
            while (await reader.ReadAsync(token).ConfigureAwait(false)) players.Add(ReadPlayer(reader));
            return new BlockMutationPlayerNameResolution(players.AsReadOnly());
        }, cancellationToken);
    }

    /// <summary>Selects target mutations from the exact ledger in strict newest-first order.</summary>
    public Task<IReadOnlyList<BlockMutationLogRow>> ReadTargetBlockMutationsAsync(BlockMutationTargetQuery query,
        CancellationToken cancellationToken = default) => ReadTargetBlockMutationsListAsync(query,
            BlockRollbackLimits.MaximumCandidates, BlockRollbackLimits.MaximumEncodedBytesPerRead, cancellationToken);

    internal Task<IReadOnlyList<BlockMutationLogRow>> ReadTargetBlockMutationsAsync(BlockMutationTargetQuery query,
        long maximumEncodedBytes, CancellationToken cancellationToken = default) => ReadTargetBlockMutationsListAsync(
            query, BlockRollbackLimits.MaximumCandidates, maximumEncodedBytes, cancellationToken);

    public Task<BlockMutationCandidatePage> ReadTargetBlockMutationPageAsync(BlockMutationTargetQuery query,
        CancellationToken cancellationToken = default) => ReadTargetBlockMutationPageAsync(query,
            BlockRollbackLimits.MaximumCandidates, BlockRollbackLimits.MaximumEncodedBytesPerRead, cancellationToken);

    internal async Task<IReadOnlyList<BlockMutationLogRow>> ReadTargetBlockMutationsListAsync(
        BlockMutationTargetQuery query, int maximumCandidates, long maximumEncodedBytes,
        CancellationToken cancellationToken = default) {
        BlockMutationCandidatePage page = await ReadTargetBlockMutationPageAsync(
            query, maximumCandidates, maximumEncodedBytes, allowTruncation: false, cancellationToken).ConfigureAwait(false);
        return page.Rows;
    }

    internal Task<BlockMutationCandidatePage> ReadTargetBlockMutationPageAsync(BlockMutationTargetQuery query,
        int maximumCandidates, long maximumEncodedBytes, CancellationToken cancellationToken = default) {
        return ReadTargetBlockMutationPageAsync(query, maximumCandidates, maximumEncodedBytes,
            allowTruncation: true, cancellationToken);
    }

    private Task<BlockMutationCandidatePage> ReadTargetBlockMutationPageAsync(BlockMutationTargetQuery query,
        int maximumCandidates, long maximumEncodedBytes, bool allowTruncation,
        CancellationToken cancellationToken) {
        ArgumentNullException.ThrowIfNull(query);
        query.Validate();
        if (maximumCandidates is <= 0 or > BlockRollbackLimits.MaximumCandidates) {
            throw new ArgumentOutOfRangeException(nameof(maximumCandidates));
        }
        ValidateEncodedByteReadLimit(maximumEncodedBytes);
        int minimumX = ClampCoordinate((long)query.CenterX - query.Radius);
        int maximumX = ClampCoordinate((long)query.CenterX + query.Radius);
        int minimumY = ClampCoordinate((long)query.CenterY - query.Radius);
        int maximumY = ClampCoordinate((long)query.CenterY + query.Radius);
        int minimumZ = ClampCoordinate((long)query.CenterZ - query.Radius);
        int maximumZ = ClampCoordinate((long)query.CenterZ + query.Radius);

        return QueueReadAsync("read exact-ledger rollback candidates", async (connection, token) => {
            await using NpgsqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT l.id, l.timestamp_utc, l.player_id, l.entry_kind, l.action_kind,
                    l.dimension, l.x, l.y, l.z, l.envelope_data, l.envelope_encoding,
                    l.source_mutation_id, l.rollback_outcome, l.failure_code, l.operator_player_id,
                    actor.playeruid, actor.last_playername, operator_player.playeruid, operator_player.last_playername
                FROM blockmutationlogs l
                LEFT JOIN players actor ON actor.id = l.player_id
                LEFT JOIN players operator_player ON operator_player.id = l.operator_player_id
                WHERE l.entry_kind = 0
                  AND ((@player_id IS NOT NULL AND l.player_id = @player_id)
                       OR (@player_uid IS NOT NULL AND actor.playeruid = @player_uid))
                  AND l.dimension = @dimension
                  AND l.x BETWEEN @minimum_x AND @maximum_x
                  AND l.y BETWEEN @minimum_y AND @maximum_y
                  AND l.z BETWEEN @minimum_z AND @maximum_z
                  AND l.id <= @cutoff_id
                  AND (@before_source_id IS NULL OR l.id < @before_source_id)
                  AND ((@break_only AND l.action_kind = 1)
                       OR (NOT @break_only AND l.action_kind IN (1, 2, 3, 4)))
                  AND NOT EXISTS (
                      SELECT 1 FROM blockmutationlogs successful
                      WHERE successful.entry_kind = 1 AND successful.rollback_outcome = 1
                        AND successful.source_mutation_id = l.id)
                ORDER BY l.id DESC
                LIMIT @row_limit;";
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, query.PlayerId);
            AddParameter(cmd, "@player_uid", NpgsqlDbType.Text, string.IsNullOrWhiteSpace(query.PlayerUid) ? null : query.PlayerUid);
            AddParameter(cmd, "@dimension", NpgsqlDbType.Integer, query.Dimension);
            AddParameter(cmd, "@minimum_x", NpgsqlDbType.Integer, minimumX);
            AddParameter(cmd, "@maximum_x", NpgsqlDbType.Integer, maximumX);
            AddParameter(cmd, "@minimum_y", NpgsqlDbType.Integer, minimumY);
            AddParameter(cmd, "@maximum_y", NpgsqlDbType.Integer, maximumY);
            AddParameter(cmd, "@minimum_z", NpgsqlDbType.Integer, minimumZ);
            AddParameter(cmd, "@maximum_z", NpgsqlDbType.Integer, maximumZ);
            AddParameter(cmd, "@cutoff_id", NpgsqlDbType.Bigint, query.CutoffId);
            AddParameter(cmd, "@before_source_id", NpgsqlDbType.Bigint, query.BeforeSourceIdExclusive);
            AddParameter(cmd, "@break_only", NpgsqlDbType.Boolean, query.BreakOnly);
            AddParameter(cmd, "@row_limit", NpgsqlDbType.Integer, maximumCandidates + 1);
            BlockMutationRowPage page = await ReadBlockMutationRowsAsync(cmd, token, maximumCandidates,
                allowTruncation, "candidate count", maximumEncodedBytes,
                "candidate encoded-byte total").ConfigureAwait(false);
            return new BlockMutationCandidatePage(page.Rows, page.HasMoreRows);
        }, cancellationToken);
    }

    /// <summary>Loads every mutation and rollback outcome for the exact candidate coordinates.</summary>
    public Task<IReadOnlyList<BlockMutationLogRow>> ReadBlockMutationHistoryAsync(BlockMutationHistoryQuery query,
        CancellationToken cancellationToken = default) => ReadBlockMutationHistoryAsync(
            query, BlockRollbackLimits.MaximumEncodedBytesPerRead, cancellationToken);

    internal Task<IReadOnlyList<BlockMutationLogRow>> ReadBlockMutationHistoryAsync(BlockMutationHistoryQuery query,
        long maximumEncodedBytes, CancellationToken cancellationToken = default) {
        ArgumentNullException.ThrowIfNull(query);
        query.Validate();
        ValidateEncodedByteReadLimit(maximumEncodedBytes);
        BlockMutationCoordinate[] coordinates = query.Coordinates.Distinct().OrderBy(value => value.Dimension)
            .ThenBy(value => value.X).ThenBy(value => value.Y).ThenBy(value => value.Z).ToArray();
        if (coordinates.Length > BlockRollbackLimits.MaximumUniqueCoordinates) {
            throw new BlockRollbackLimitExceededException("unique coordinate count", BlockRollbackLimits.MaximumUniqueCoordinates);
        }
        if (coordinates.Length == 0) {
            return QueueReadAsync("read empty exact-ledger coordinate history",
                (_, token) => {
                    token.ThrowIfCancellationRequested();
                    return Task.FromResult<IReadOnlyList<BlockMutationLogRow>>(Array.Empty<BlockMutationLogRow>());
                }, cancellationToken);
        }

        return QueueReadAsync("read exact-ledger coordinate history", async (connection, token) => {
            await using NpgsqlCommand cmd = connection.CreateCommand();
            cmd.CommandText = @"WITH requested(dimension, x, y, z) AS (
                    SELECT * FROM unnest(@dimensions, @xs, @ys, @zs)
                )
                SELECT l.id, l.timestamp_utc, l.player_id, l.entry_kind, l.action_kind,
                    l.dimension, l.x, l.y, l.z, l.envelope_data, l.envelope_encoding,
                    l.source_mutation_id, l.rollback_outcome, l.failure_code, l.operator_player_id,
                    actor.playeruid, actor.last_playername, operator_player.playeruid, operator_player.last_playername
                FROM requested requested_coordinate
                JOIN blockmutationlogs l
                  ON l.dimension = requested_coordinate.dimension
                 AND l.x = requested_coordinate.x AND l.y = requested_coordinate.y AND l.z = requested_coordinate.z
                LEFT JOIN players actor ON actor.id = l.player_id
                LEFT JOIN players operator_player ON operator_player.id = l.operator_player_id
                WHERE l.id BETWEEN @minimum_id AND @maximum_id
                  AND (
                    (l.entry_kind = 0 AND NOT EXISTS (
                        SELECT 1 FROM blockmutationlogs success
                        WHERE success.entry_kind = 1 AND success.rollback_outcome = 1
                          AND success.source_mutation_id = l.id AND success.id <= @maximum_id))
                    OR (l.entry_kind = 1 AND l.rollback_outcome = 1
                        AND l.source_mutation_id < @minimum_id)
                    OR (l.entry_kind = 1 AND l.rollback_outcome = 2
                        AND l.id = (SELECT max(latest_failure.id) FROM blockmutationlogs latest_failure
                            WHERE latest_failure.entry_kind = 1
                              AND latest_failure.rollback_outcome = 2
                              AND latest_failure.source_mutation_id = l.source_mutation_id
                              AND latest_failure.id <= @maximum_id)
                        AND NOT EXISTS (SELECT 1 FROM blockmutationlogs later_success
                            WHERE later_success.entry_kind = 1
                              AND later_success.rollback_outcome = 1
                              AND later_success.source_mutation_id = l.source_mutation_id
                              AND later_success.id > l.id AND later_success.id <= @maximum_id))
                  )
                ORDER BY l.id DESC
                LIMIT @row_limit;";
            AddParameter(cmd, "@dimensions", NpgsqlDbType.Array | NpgsqlDbType.Integer, coordinates.Select(value => value.Dimension).ToArray());
            AddParameter(cmd, "@xs", NpgsqlDbType.Array | NpgsqlDbType.Integer, coordinates.Select(value => value.X).ToArray());
            AddParameter(cmd, "@ys", NpgsqlDbType.Array | NpgsqlDbType.Integer, coordinates.Select(value => value.Y).ToArray());
            AddParameter(cmd, "@zs", NpgsqlDbType.Array | NpgsqlDbType.Integer, coordinates.Select(value => value.Z).ToArray());
            AddParameter(cmd, "@maximum_id", NpgsqlDbType.Bigint, query.MaximumId);
            AddParameter(cmd, "@row_limit", NpgsqlDbType.Integer, BlockRollbackLimits.MaximumHistoryRows + 1);
            AddParameter(cmd, "@minimum_id", NpgsqlDbType.Bigint, query.MinimumId);
            return (await ReadBlockMutationRowsAsync(cmd, token, BlockRollbackLimits.MaximumHistoryRows,
                allowTruncation: false, "history row count", maximumEncodedBytes,
                "history encoded-byte total").ConfigureAwait(false)).Rows;
        }, cancellationToken);
    }

    private static BlockMutationPlayer ReadPlayer(NpgsqlDataReader reader) => new(
        reader.GetInt64(0), reader.IsDBNull(1) ? null : reader.GetString(1), reader.IsDBNull(2) ? null : reader.GetString(2));

    private static async Task<BlockMutationRowPage> ReadBlockMutationRowsAsync(NpgsqlCommand cmd,
        CancellationToken cancellationToken, int maximumRows, bool allowTruncation, string rowLimitName,
        long maximumEncodedBytes, string byteLimitName) {
        var rows = new List<BlockMutationLogRow>();
        long encodedBytes = 0;
        await using NpgsqlDataReader reader = await cmd.ExecuteReaderAsync(cancellationToken).ConfigureAwait(false);
        while (await reader.ReadAsync(cancellationToken).ConfigureAwait(false)) {
            if (rows.Count >= maximumRows) {
                if (allowTruncation) return new BlockMutationRowPage(rows.AsReadOnly(), true);
                throw new BlockRollbackLimitExceededException(rowLimitName, maximumRows);
            }
            long envelopeLength = reader.GetBytes(9, 0, null, 0, 0);
            if (envelopeLength > maximumEncodedBytes - encodedBytes) {
                if (allowTruncation && rows.Count != 0) {
                    return new BlockMutationRowPage(rows.AsReadOnly(), true);
                }
                throw new BlockRollbackLimitExceededException(byteLimitName, maximumEncodedBytes);
            }
            encodedBytes += envelopeLength;
            rows.Add(new BlockMutationLogRow(
                reader.GetInt64(0), reader.GetInt64(1), reader.IsDBNull(2) ? null : reader.GetInt64(2),
                (BlockMutationEntryKind)reader.GetInt32(3), (BlockMutationActionKind)reader.GetInt32(4),
                reader.GetInt32(5), reader.GetInt32(6), reader.GetInt32(7), reader.GetInt32(8),
                reader.GetFieldValue<byte[]>(9), reader.GetInt32(10), reader.IsDBNull(11) ? null : reader.GetInt64(11),
                reader.IsDBNull(12) ? null : (BlockMutationRollbackOutcome)reader.GetInt32(12),
                reader.IsDBNull(13) ? null : reader.GetString(13), reader.IsDBNull(14) ? null : reader.GetInt64(14),
                reader.IsDBNull(15) ? null : reader.GetString(15), reader.IsDBNull(16) ? null : reader.GetString(16),
                reader.IsDBNull(17) ? null : reader.GetString(17), reader.IsDBNull(18) ? null : reader.GetString(18)
            ));
        }
        return new BlockMutationRowPage(rows.AsReadOnly(), false);
    }

    private sealed record BlockMutationRowPage(IReadOnlyList<BlockMutationLogRow> Rows, bool HasMoreRows);

    private static void ValidateEncodedByteReadLimit(long maximumEncodedBytes) {
        if (maximumEncodedBytes is <= 0 or > BlockRollbackLimits.MaximumEncodedBytesPerRead) {
            throw new ArgumentOutOfRangeException(nameof(maximumEncodedBytes));
        }
    }

    private static int ClampCoordinate(long value) => value < int.MinValue ? int.MinValue
        : value > int.MaxValue ? int.MaxValue : (int)value;

    public void AddBlockLog(string? playername, string? playeruid, string actiontype, string block, string? itemstack, int x, int y, int z, int? oldblockid) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO blocklogs (timestamp_utc, player_id, actiontype, block, itemstack_data, itemstack_encoding, x, y, z, oldblockid)
            VALUES (@timestamp, @player_id, @actiontype, @block, @itemstack_data, @itemstack_encoding, @x, @y, @z, @oldblockid)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 0);
            AddParameter(cmd, "@block", NpgsqlDbType.Text, block);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@oldblockid", NpgsqlDbType.Integer, oldblockid);

            cmd.ExecuteNonQuery();
        });
    }

    public void RollbackBreaks(IServerPlayer player, int groupId, int x, int y, int z, int radius, string playername) {
        // Read on a separate thread/connection to not block main thread
        QueueRead("rollback breaks", () => {
            using var connection = dataSource.OpenConnection();

            using var cmd = connection.CreateCommand();

            cmd.CommandText = @"SELECT id FROM players
            WHERE last_playername = @playername
            LIMIT 1";
            AddParameter(cmd, "@playername", NpgsqlDbType.Text, playername);
            long playerid;
            using (var reader = cmd.ExecuteReader()) {
                if (!reader.Read()) {
                    Main.API.Event.EnqueueMainThreadTask(() => {
                        Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, "No player logged with that username.", EnumChatType.CommandSuccess);
                    }, "SendRollbackFail");
                    return;
                }
                playerid = reader.GetInt64(0);
            }

            cmd.Parameters.Clear();
            cmd.CommandText = RollbackBreaksQuery;

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@playerid", NpgsqlDbType.Bigint, playerid);

            Dictionary<string, (BlockPos, long, int)> rollbackToSet = new();

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(0);

                        string block = reader.IsDBNull(1) ? "" : reader.GetString(1);
                        if (block.Contains("chiseled"))
                            continue;

                        int indexOfIDChar = block.IndexOf('/');
                        if (indexOfIDChar == -1)
                            continue;
                        string blockIDStr = block.Substring(indexOfIDChar + 1, block.Length - indexOfIDChar - 1);

                        int blockID = Convert.ToInt32(blockIDStr);
                        if (blockID == 0)
                            continue;

                        int logX = reader.GetInt32(2);
                        int logY = reader.GetInt32(3);
                        int logZ = reader.GetInt32(4);

                        string currentRollbackValueKey = logX + "|" + logY + "|" + logZ;
                        try {
                            (BlockPos, long, int) currentRollbackValue = rollbackToSet[currentRollbackValueKey];
                            if (currentRollbackValue.Item2 > tsSeconds) {
                                BlockPos savedBlockPos = rollbackToSet[currentRollbackValueKey].Item1;
                                rollbackToSet[currentRollbackValueKey] = (savedBlockPos, tsSeconds, blockID);
                            }
                        }
                        catch (KeyNotFoundException) {
                            BlockPos blockPos = new BlockPos(logX + (int)Main.API.World.DefaultSpawnPosition.X, logY, logZ + (int)Main.API.World.DefaultSpawnPosition.Z);
                            rollbackToSet[currentRollbackValueKey] = (blockPos, tsSeconds, blockID);
                        }
                    }
                    logs.Add("Rolled back blocks broken by " + playername + " in a radius of " + radius + ".");
                }
                else {
                    logs.Add("Nothing to rollback.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (KeyValuePair<string, (BlockPos, long, int)> entry in rollbackToSet) {
                    Main.API.World.BlockAccessor.SetBlock(entry.Value.Item3, entry.Value.Item1);
                }

                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendRollback");
        });
    }

    public void CheckBlockLog(int pageNum, IServerPlayer player, int groupId, int x, int y, int z, int radius) {
        // Read on a separate thread/connection to not block main thread
        QueueRead("check block log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT b.id, b.timestamp_utc, p.last_playername, p.playeruid, b.actiontype, b.block, b.itemstack_data, b.itemstack_encoding, b.x, b.y, b.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, block, itemstack_data, itemstack_encoding, x, y, z FROM blocklogs
            WHERE x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) b
            LEFT JOIN players p ON b.player_id = p.id
            ORDER BY b.id ASC";

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/blocklog -r " + radius + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string block = reader.IsDBNull(5) ? "" : reader.GetString(5);

                        byte[]? itemstackData = reader.IsDBNull(6) ? null : (byte[])reader[6];
                        int itemstackEncoding = reader.GetInt32(7);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(8);
                        int logY = reader.GetInt32(9);
                        int logZ = reader.GetInt32(10);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {5} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4} " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{6}, {7}, {8}</font></strong>", timestamp, playername, playeruid, actiontype, block, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No block logs found here.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendBlockLog");
        });
    }

    public void AddEntityLog(string? playername, string? playeruid, string actiontype, string entityname, string entityid, string? itemstack, int x, int y, int z) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO entitylogs (timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z)
            VALUES (@timestamp, @player_id, @actiontype, @entityname, @entityid, @itemstack_data, @itemstack_encoding, @x, @y, @z)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 3);
            AddParameter(cmd, "@entityname", NpgsqlDbType.Text, entityname);
            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityid);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);

            cmd.ExecuteNonQuery();
        });
    }

    public void CheckEntityLog(int pageNum, IServerPlayer player, int groupId, int x, int y, int z, int radius) {
        QueueRead("check entity log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT e.id, e.timestamp_utc, p.last_playername, p.playeruid, e.actiontype, e.entityname, e.entityid, e.itemstack_data, e.itemstack_encoding, e.x, e.y, e.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z FROM entitylogs
            WHERE x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) e
            LEFT JOIN players p ON e.player_id = p.id
            ORDER BY e.id ASC";

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/entitylog -r " + radius + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string entityname = reader.IsDBNull(5) ? "" : reader.GetString(5);
                        string entityid = reader.IsDBNull(6) ? "" : reader.GetString(6);

                        byte[]? itemstackData = reader.IsDBNull(7) ? null : (byte[])reader[7];
                        int itemstackEncoding = reader.GetInt32(8);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(9);
                        int logY = reader.GetInt32(10);
                        int logZ = reader.GetInt32(11);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {6} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4}({5}) " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{7}, {8}, {9}</font></strong>", timestamp, playername, playeruid, actiontype, entityname, entityid, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No entity logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendEntityLog");
        });
    }

    public void CheckEntityLogWithEntityID(int pageNum, IServerPlayer player, int groupId, string entityID) {
        QueueRead("check entity log by entity ID", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = EntityLogByEntityIdQuery;

            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityID);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/entitylog -e " + entityID + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string entityname = reader.IsDBNull(5) ? "" : reader.GetString(5);
                        string entityid = reader.IsDBNull(6) ? "" : reader.GetString(6);

                        byte[]? itemstackData = reader.IsDBNull(7) ? null : (byte[])reader[7];
                        int itemstackEncoding = reader.GetInt32(8);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(9);
                        int logY = reader.GetInt32(10);
                        int logZ = reader.GetInt32(11);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {6} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4}({5}) " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{7}, {8}, {9}</font></strong>", timestamp, playername, playeruid, actiontype, entityname, entityid, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No entity logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendEntityLogWithEntityID");
        });
    }

    public (int, int, int)? GetLastEntityCoordsLog(string entityID) {
        const string operation = "get last entity coordinates";
        if (!TryBeginRead(operation)) return null;

        try {
            using var connection = dataSource.OpenConnection();

            using var cmd = connection.CreateCommand();
            cmd.CommandText = LastEntityCoordsQuery;

            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityID);

            using var reader = cmd.ExecuteReader();
            if (reader.Read()) {
                int x = reader.GetInt32(0);
                int y = reader.GetInt32(1);
                int z = reader.GetInt32(2);

                return (x, y, z);
            }
            return null;
        }
        catch (Exception ex) {
            LogError("GriefLedger: Database read '" + operation + "' failed: " + ex);
            throw;
        }
        finally {
            EndRead();
        }
    }

    public void AddContainerLog(string? playername, string? playeruid, string actiontype, string containerid, string? itemstack, int quantity) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO containerlogs (timestamp_utc, player_id, containerid, itemstack_data, itemstack_encoding, quantity, actiontype)
            VALUES (@timestamp, @player_id, @containerid, @itemstack_data, @itemstack_encoding, @quantity, @actiontype)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 5);
            AddParameter(cmd, "@containerid", NpgsqlDbType.Text, containerid);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@quantity", NpgsqlDbType.Integer, quantity);

            cmd.ExecuteNonQuery();
        });
    }

    public void CheckContainerLog(int pageNum, IServerPlayer player, int groupId, string containerid) {
        CheckContainerLog(pageNum, player, groupId, new List<string> { containerid });
    }

    public void CheckContainerLog(int pageNum, IServerPlayer player, int groupId, List<string> containerids) {
        QueueRead("check container log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = ContainerLogQuery;

            AddParameter(cmd, "@containerids", NpgsqlDbType.Array | NpgsqlDbType.Text, containerids.ToArray());
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/containerlog -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string logPlayername = reader.IsDBNull(2) ? "Unknown" : reader.GetString(2);
                        string logPlayeruid = reader.IsDBNull(3) ? "Unknown" : reader.GetString(3);

                        string logContainerid = reader.IsDBNull(4) ? "" : reader.GetString(4);

                        byte[]? itemstackData = reader.IsDBNull(5) ? null : (byte[])reader[5];
                        int itemstackEncoding = reader.GetInt32(6);
                        string itemstack = DecompressText(itemstackData, itemstackEncoding) ?? "";

                        int quantity = reader.GetInt32(7);

                        int actiontypeInt = reader.IsDBNull(8) ? 5 : reader.GetInt32(8); // 5 is TAKEN
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "TAKEN";

                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | <strong>{1}</strong>({2}) {6} {5}x{4} in <strong><font color=\"#9BD1EC\">{3}</font></strong>", timestamp, logPlayername, logPlayeruid, logContainerid, itemstack, quantity, actiontype);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No container logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendContainerLog");
        });
    }

    public void Dispose() {
        lock (lifecycleLock) {
            if (disposed) return;
            acceptingWrites = false;
            acceptingReads = false;
            databaseTasks.CompleteAdding();
            disposed = true;
        }

        workerThread.Join();
        readsDrained.Wait();
        databaseTasks.Dispose();
        readsDrained.Dispose();
        dataSource.Dispose();
    }
}
