using Npgsql;
using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using NpgsqlTypes;
using Vintagestory.API.Common;
using Vintagestory.API.Config;
using Vintagestory.API.MathTools;
using Vintagestory.API.Server;

namespace GriefLedger;

public class Database : IDisposable {
    private int logLimit = 4;
    private readonly NpgsqlDataSource dataSource;

    private readonly Thread workerThread;
    private readonly BlockingCollection<Action<NpgsqlConnection>> databaseTasks;
    private readonly object lifecycleLock = new object();
    private readonly ManualResetEventSlim readsDrained = new ManualResetEventSlim(true);
    private bool acceptingWrites = true;
    private bool acceptingReads = true;
    private int activeReads;
    private bool disposed;

    private const string CreatePlayersTable = @"CREATE TABLE IF NOT EXISTS players (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        playeruid TEXT UNIQUE,
        last_playername TEXT
    )";
    private const string CreateBlockLogsTable = @"CREATE TABLE IF NOT EXISTS blocklogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        actiontype INTEGER,
        block TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        x INTEGER,
        y INTEGER,
        z INTEGER,
        oldblockid INTEGER
    )";
    private const string CreateEntityLogsTable = @"CREATE TABLE IF NOT EXISTS entitylogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        actiontype INTEGER,
        entityname TEXT,
        entityid TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        x INTEGER,
        y INTEGER,
        z INTEGER
    )";
    private const string CreateContainerLogsTable = @"CREATE TABLE IF NOT EXISTS containerlogs (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        timestamp_utc BIGINT,
        player_id BIGINT NULL,
        containerid TEXT,
        itemstack_data BYTEA NULL,
        itemstack_encoding INTEGER NOT NULL DEFAULT 0,
        quantity INTEGER,
        actiontype INTEGER
    )";

    internal const string RollbackBreaksQuery = @"SELECT timestamp_utc, block, x, y, z FROM blocklogs
            WHERE player_id = @playerid
            AND actiontype = 0
            AND x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius";

    internal const string EntityLogByEntityIdQuery = @"SELECT e.id, e.timestamp_utc, p.last_playername, p.playeruid, e.actiontype, e.entityname, e.entityid, e.itemstack_data, e.itemstack_encoding, e.x, e.y, e.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z FROM entitylogs
            WHERE entityid = @entityid
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) e
            LEFT JOIN players p ON e.player_id = p.id
            ORDER BY e.id ASC";

    internal const string LastEntityCoordsQuery = @"SELECT x, y, z
            FROM entitylogs
            WHERE entityid = @entityid
            ORDER BY id DESC
            LIMIT 1";

    internal const string ContainerLogQuery = @"SELECT c.id, c.timestamp_utc, p.last_playername, p.playeruid, c.containerid, c.itemstack_data, c.itemstack_encoding, c.quantity, c.actiontype
                FROM (
                    SELECT id, timestamp_utc, player_id, containerid, itemstack_data, itemstack_encoding, quantity, actiontype
                    FROM containerlogs
                    WHERE containerid = ANY(@containerids)
                    ORDER BY id DESC
                    LIMIT @loglimit OFFSET @skiplognum
                ) c
                LEFT JOIN players p ON c.player_id = p.id
                ORDER BY c.id ASC";

    private static readonly Dictionary<string, Dictionary<string, string>> RequiredColumnTypes = new() {
        ["players"] = new() { ["id"] = "bigint", ["playeruid"] = "text", ["last_playername"] = "text" },
        ["blocklogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["actiontype"] = "integer", ["block"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["x"] = "integer", ["y"] = "integer", ["z"] = "integer", ["oldblockid"] = "integer" },
        ["entitylogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["actiontype"] = "integer", ["entityname"] = "text", ["entityid"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["x"] = "integer", ["y"] = "integer", ["z"] = "integer" },
        ["containerlogs"] = new() { ["id"] = "bigint", ["timestamp_utc"] = "bigint", ["player_id"] = "bigint", ["containerid"] = "text", ["itemstack_data"] = "bytea", ["itemstack_encoding"] = "integer", ["quantity"] = "integer", ["actiontype"] = "integer" }
    };

    public enum ActionType {
        BROKE = 0,
        PLACED = 1,
        USED = 2,
        INTERACTED = 3,
        KILLED = 4,
        TAKEN = 5,
        SWAP = 6,
        SAME_ITEM = 7,
        SPAWNED = 8,
        DESPAWNED = 9
    }

    private static readonly Dictionary<string, int> ActionTypeMap = new Dictionary<string, int> {
        { "BROKE", (int)ActionType.BROKE },
        { "PLACED", (int)ActionType.PLACED },
        { "USED", (int)ActionType.USED },
        { "INTERACTED", (int)ActionType.INTERACTED },
        { "KILLED", (int)ActionType.KILLED },
        { "TAKEN", (int)ActionType.TAKEN },
        { "SWAP", (int)ActionType.SWAP },
        { "SAME_ITEM", (int)ActionType.SAME_ITEM },
        { "SPAWNED", (int)ActionType.SPAWNED },
        { "DESPAWNED", (int)ActionType.DESPAWNED }
    };

    private static readonly Dictionary<int, string> ReverseActionTypeMap = new Dictionary<int, string> {
        { (int)ActionType.BROKE, "BROKE" },
        { (int)ActionType.PLACED, "PLACED" },
        { (int)ActionType.USED, "USED" },
        { (int)ActionType.INTERACTED, "INTERACTED" },
        { (int)ActionType.KILLED, "KILLED" },
        { (int)ActionType.TAKEN, "TAKEN" },
        { (int)ActionType.SWAP, "SWAP" },
        { (int)ActionType.SAME_ITEM, "SAME_ITEM" },
        { (int)ActionType.SPAWNED, "SPAWNED" },
        { (int)ActionType.DESPAWNED, "DESPAWNED" }
    };

    public Database() {
        dataSource = DatabaseConfiguration.CreateDataSource();
        try {
            using (var connection = dataSource.OpenConnection()) {
                using (var versionCmd = connection.CreateCommand()) {
                    versionCmd.CommandText = "SHOW server_version_num;";
                    if (Convert.ToInt32(versionCmd.ExecuteScalar()) < 170000) {
                        throw new InvalidOperationException("GriefLedger requires PostgreSQL 17 or newer.");
                    }
                }

                using var transaction = connection.BeginTransaction();
                using (var cmd = connection.CreateCommand()) {
                    cmd.Transaction = transaction;
                    cmd.CommandText = CreatePlayersTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateBlockLogsTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateEntityLogsTable;
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = CreateContainerLogsTable;
                    cmd.ExecuteNonQuery();

                    ValidateSchema(connection, transaction);

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_coords ON blocklogs(x, y, z);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_coords ON entitylogs(x, y, z);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_id ON containerlogs(containerid);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_entityid_id_desc ON entitylogs(entityid, id DESC);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_containerid_id_desc ON containerlogs(containerid, id DESC);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_ts ON blocklogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_pid_ts ON blocklogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_blocklogs_act_ts ON blocklogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_ts ON entitylogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_pid_ts ON entitylogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_entitylogs_act_ts ON entitylogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();

                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_ts ON containerlogs(timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_pid_ts ON containerlogs(player_id, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                    cmd.CommandText = "CREATE INDEX IF NOT EXISTS idx_containerlogs_act_ts ON containerlogs(actiontype, timestamp_utc);";
                    cmd.ExecuteNonQuery();
                }
                transaction.Commit();
            }
        }
        catch {
            dataSource.Dispose();
            throw;
        }

        databaseTasks = new BlockingCollection<Action<NpgsqlConnection>>(new ConcurrentQueue<Action<NpgsqlConnection>>());
        workerThread = new Thread(WorkerLoop);
        workerThread.IsBackground = true;
        workerThread.Name = "GriefLedger database writer";
        workerThread.Start();
    }

    private static void ValidateSchema(NpgsqlConnection connection, NpgsqlTransaction transaction) {
        var actualColumns = new Dictionary<string, Dictionary<string, (string Type, bool IsIdentity)>>(StringComparer.Ordinal);
        using var cmd = connection.CreateCommand();
        cmd.Transaction = transaction;
        cmd.CommandText = @"SELECT table_name, column_name, data_type, is_identity
            FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = ANY(@tables);";
        AddParameter(cmd, "@tables", NpgsqlDbType.Array | NpgsqlDbType.Text, new[] { "players", "blocklogs", "entitylogs", "containerlogs" });
        using (var reader = cmd.ExecuteReader()) {
            while (reader.Read()) {
                string table = reader.GetString(0);
                if (!actualColumns.TryGetValue(table, out var columns)) {
                    columns = new Dictionary<string, (string Type, bool IsIdentity)>(StringComparer.Ordinal);
                    actualColumns[table] = columns;
                }
                columns[reader.GetString(1)] = (reader.GetString(2), reader.GetString(3) == "YES");
            }
        }

        foreach (var table in RequiredColumnTypes) {
            if (!actualColumns.TryGetValue(table.Key, out var columns)) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: required table " + table.Key + " was not found in the current schema.");
            }
            foreach (var expectedColumn in table.Value) {
                if (!columns.TryGetValue(expectedColumn.Key, out var actual)) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: required column " + table.Key + "." + expectedColumn.Key + " was not found.");
                }
                if (!String.Equals(actual.Type, expectedColumn.Value, StringComparison.Ordinal)) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: " + table.Key + "." + expectedColumn.Key + " must use PostgreSQL type " + expectedColumn.Value + ".");
                }
                if (expectedColumn.Key == "id" && !actual.IsIdentity) {
                    throw new InvalidOperationException("GriefLedger database schema validation failed: " + table.Key + ".id must be an identity column.");
                }
            }
        }

        foreach (string tableName in RequiredColumnTypes.Keys) {
            cmd.Parameters.Clear();
            cmd.CommandText = @"SELECT EXISTS (
                SELECT 1
                FROM pg_catalog.pg_constraint constraint_row
                JOIN pg_catalog.pg_class table_row ON table_row.oid = constraint_row.conrelid
                JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
                JOIN pg_catalog.pg_attribute id_column
                  ON id_column.attrelid = table_row.oid
                 AND id_column.attname = 'id'
                 AND NOT id_column.attisdropped
                WHERE schema_row.nspname = current_schema()
                  AND table_row.relname = @table_name
                  AND constraint_row.contype = 'p'
                  AND NOT constraint_row.condeferrable
                  AND NOT constraint_row.condeferred
                  AND constraint_row.convalidated
                  AND constraint_row.conkey = ARRAY[id_column.attnum]::smallint[]
            );";
            AddParameter(cmd, "@table_name", NpgsqlDbType.Text, tableName);
            if (!(bool)(cmd.ExecuteScalar() ?? false)) {
                throw new InvalidOperationException("GriefLedger database schema validation failed: " + tableName + ".id must be the sole column of a validated, non-deferrable primary key.");
            }
        }

        cmd.Parameters.Clear();
        cmd.CommandText = @"SELECT EXISTS (
            SELECT 1
            FROM pg_catalog.pg_index index_row
            JOIN pg_catalog.pg_class table_row ON table_row.oid = index_row.indrelid
            JOIN pg_catalog.pg_namespace schema_row ON schema_row.oid = table_row.relnamespace
            JOIN pg_catalog.pg_attribute uid_column
              ON uid_column.attrelid = table_row.oid
             AND uid_column.attname = 'playeruid'
             AND NOT uid_column.attisdropped
            WHERE schema_row.nspname = current_schema()
              AND table_row.relname = 'players'
              AND index_row.indisunique
              AND index_row.indimmediate
              AND index_row.indisvalid
              AND index_row.indisready
              AND index_row.indpred IS NULL
              AND index_row.indexprs IS NULL
              AND index_row.indnkeyatts = 1
              AND index_row.indkey[0] = uid_column.attnum
        );";
        if (!(bool)(cmd.ExecuteScalar() ?? false)) {
            throw new InvalidOperationException("GriefLedger database schema validation failed: players.playeruid must have a valid, immediate, non-partial single-column unique index usable by ON CONFLICT.");
        }
    }

    private void WorkerLoop() {
        foreach (var task in databaseTasks.GetConsumingEnumerable()) {
            try {
                using (var connection = dataSource.OpenConnection()) {
                    task(connection);
                }
            }
            catch (Exception ex) {
                LogError("GriefLedger: A queued database write failed and was not retried: " + ex);
            }
        }
    }

    private static void LogError(string message) {
        Main.API?.Logger.Error(message);
    }

    private void QueueWrite(Action<NpgsqlConnection> task) {
        lock (lifecycleLock) {
            if (!acceptingWrites) {
                LogError("GriefLedger: Rejected a database write because the database is shutting down.");
                return;
            }
            databaseTasks.Add(task);
        }
    }

    private bool TryBeginRead(string operation) {
        lock (lifecycleLock) {
            if (!acceptingReads) {
                LogError("GriefLedger: Rejected database read '" + operation + "' because the database is shutting down.");
                return false;
            }
            activeReads++;
            readsDrained.Reset();
            return true;
        }
    }

    private void EndRead() {
        lock (lifecycleLock) {
            activeReads--;
            if (activeReads == 0) readsDrained.Set();
        }
    }

    private void QueueRead(string operation, Action read) {
        if (!TryBeginRead(operation)) return;

        try {
            Task.Run(() => {
                try {
                    read();
                }
                catch (Exception ex) {
                    LogError("GriefLedger: Database read '" + operation + "' failed: " + ex);
                }
                finally {
                    EndRead();
                }
            });
        }
        catch (Exception ex) {
            EndRead();
            LogError("GriefLedger: Database read '" + operation + "' could not be scheduled: " + ex);
        }
    }

    private static void AddParameter(NpgsqlCommand cmd, string name, NpgsqlDbType type, object? value) {
        cmd.Parameters.Add(new NpgsqlParameter(name, type) { Value = value ?? DBNull.Value });
    }

    public (byte[]? data, int encoding) CompressText(string? value) {
        if (value == null) return (null, 0);

        byte[] utf8Bytes = System.Text.Encoding.UTF8.GetBytes(value);
        using var outputStream = new MemoryStream();
        using (var brotliStream = new System.IO.Compression.BrotliStream(outputStream, System.IO.Compression.CompressionLevel.Optimal)) {
            brotliStream.Write(utf8Bytes, 0, utf8Bytes.Length);
        }

        byte[] compressedBytes = outputStream.ToArray();
        if (compressedBytes.Length < utf8Bytes.Length) {
            return (compressedBytes, 2);
        }
        return (utf8Bytes, 1);
    }

    public string? DecompressText(byte[]? data, int encoding) {
        if (data == null || encoding == 0) return null;
        if (encoding == 1) return System.Text.Encoding.UTF8.GetString(data);
        if (encoding == 2) {
            using var inputStream = new MemoryStream(data);
            using var brotliStream = new System.IO.Compression.BrotliStream(inputStream, System.IO.Compression.CompressionMode.Decompress);
            using var outputStream = new MemoryStream();
            brotliStream.CopyTo(outputStream);
            return System.Text.Encoding.UTF8.GetString(outputStream.ToArray());
        }
        return null;
    }

    private long GetOrInsertPlayer(NpgsqlConnection connection, string? playername, string? playeruid) {
        if (playername == null && playeruid == null) return -1;

        using var cmd = connection.CreateCommand();
        if (playeruid != null) {
            cmd.CommandText = @"INSERT INTO players (playeruid, last_playername)
                VALUES (@uid, @name)
                ON CONFLICT (playeruid) DO UPDATE
                SET last_playername = EXCLUDED.last_playername
                RETURNING id;";
            AddParameter(cmd, "@uid", NpgsqlDbType.Text, playeruid);
            AddParameter(cmd, "@name", NpgsqlDbType.Text, playername);
            return Convert.ToInt64(cmd.ExecuteScalar());
        }
        else {
            cmd.CommandText = "INSERT INTO players (last_playername) VALUES (@name) RETURNING id;";
            AddParameter(cmd, "@name", NpgsqlDbType.Text, playername);
            return Convert.ToInt64(cmd.ExecuteScalar());
        }
    }

    public void AddBlockLog(string? playername, string? playeruid, string actiontype, string block, string? itemstack, int x, int y, int z, int? oldblockid) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO blocklogs (timestamp_utc, player_id, actiontype, block, itemstack_data, itemstack_encoding, x, y, z, oldblockid)
            VALUES (@timestamp, @player_id, @actiontype, @block, @itemstack_data, @itemstack_encoding, @x, @y, @z, @oldblockid)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 0);
            AddParameter(cmd, "@block", NpgsqlDbType.Text, block);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@oldblockid", NpgsqlDbType.Integer, oldblockid);

            cmd.ExecuteNonQuery();
        });
    }

    public void RollbackBreaks(IServerPlayer player, int groupId, int x, int y, int z, int radius, string playername) {
        // Read on a separate thread/connection to not block main thread
        QueueRead("rollback breaks", () => {
            using var connection = dataSource.OpenConnection();

            using var cmd = connection.CreateCommand();

            cmd.CommandText = @"SELECT id FROM players
            WHERE last_playername = @playername
            LIMIT 1";
            AddParameter(cmd, "@playername", NpgsqlDbType.Text, playername);
            long playerid;
            using (var reader = cmd.ExecuteReader()) {
                if (!reader.Read()) {
                    Main.API.Event.EnqueueMainThreadTask(() => {
                        Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, "No player logged with that username.", EnumChatType.CommandSuccess);
                    }, "SendRollbackFail");
                    return;
                }
                playerid = reader.GetInt64(0);
            }

            cmd.Parameters.Clear();
            cmd.CommandText = RollbackBreaksQuery;

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@playerid", NpgsqlDbType.Bigint, playerid);

            Dictionary<string, (BlockPos, long, int)> rollbackToSet = new();

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(0);

                        string block = reader.IsDBNull(1) ? "" : reader.GetString(1);
                        if (block.Contains("chiseled"))
                            continue;

                        int indexOfIDChar = block.IndexOf('/');
                        if (indexOfIDChar == -1)
                            continue;
                        string blockIDStr = block.Substring(indexOfIDChar + 1, block.Length - indexOfIDChar - 1);

                        int blockID = Convert.ToInt32(blockIDStr);
                        if (blockID == 0)
                            continue;

                        int logX = reader.GetInt32(2);
                        int logY = reader.GetInt32(3);
                        int logZ = reader.GetInt32(4);

                        string currentRollbackValueKey = logX + "|" + logY + "|" + logZ;
                        try {
                            (BlockPos, long, int) currentRollbackValue = rollbackToSet[currentRollbackValueKey];
                            if (currentRollbackValue.Item2 > tsSeconds) {
                                BlockPos savedBlockPos = rollbackToSet[currentRollbackValueKey].Item1;
                                rollbackToSet[currentRollbackValueKey] = (savedBlockPos, tsSeconds, blockID);
                            }
                        }
                        catch (KeyNotFoundException) {
                            BlockPos blockPos = new BlockPos(logX + (int)Main.API.World.DefaultSpawnPosition.X, logY, logZ + (int)Main.API.World.DefaultSpawnPosition.Z);
                            rollbackToSet[currentRollbackValueKey] = (blockPos, tsSeconds, blockID);
                        }
                    }
                    logs.Add("Rolled back blocks broken by " + playername + " in a radius of " + radius + ".");
                }
                else {
                    logs.Add("Nothing to rollback.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (KeyValuePair<string, (BlockPos, long, int)> entry in rollbackToSet) {
                    Main.API.World.BlockAccessor.SetBlock(entry.Value.Item3, entry.Value.Item1);
                }

                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendRollback");
        });
    }

    public void CheckBlockLog(int pageNum, IServerPlayer player, int groupId, int x, int y, int z, int radius) {
        // Read on a separate thread/connection to not block main thread
        QueueRead("check block log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT b.id, b.timestamp_utc, p.last_playername, p.playeruid, b.actiontype, b.block, b.itemstack_data, b.itemstack_encoding, b.x, b.y, b.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, block, itemstack_data, itemstack_encoding, x, y, z FROM blocklogs
            WHERE x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) b
            LEFT JOIN players p ON b.player_id = p.id
            ORDER BY b.id ASC";

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/blocklog -r " + radius + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string block = reader.IsDBNull(5) ? "" : reader.GetString(5);

                        byte[]? itemstackData = reader.IsDBNull(6) ? null : (byte[])reader[6];
                        int itemstackEncoding = reader.GetInt32(7);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(8);
                        int logY = reader.GetInt32(9);
                        int logZ = reader.GetInt32(10);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {5} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4} " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{6}, {7}, {8}</font></strong>", timestamp, playername, playeruid, actiontype, block, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No block logs found here.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendBlockLog");
        });
    }

    public void AddEntityLog(string? playername, string? playeruid, string actiontype, string entityname, string entityid, string? itemstack, int x, int y, int z) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO entitylogs (timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z)
            VALUES (@timestamp, @player_id, @actiontype, @entityname, @entityid, @itemstack_data, @itemstack_encoding, @x, @y, @z)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 3);
            AddParameter(cmd, "@entityname", NpgsqlDbType.Text, entityname);
            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityid);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);

            cmd.ExecuteNonQuery();
        });
    }

    public void CheckEntityLog(int pageNum, IServerPlayer player, int groupId, int x, int y, int z, int radius) {
        QueueRead("check entity log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"SELECT e.id, e.timestamp_utc, p.last_playername, p.playeruid, e.actiontype, e.entityname, e.entityid, e.itemstack_data, e.itemstack_encoding, e.x, e.y, e.z FROM (
            SELECT id, timestamp_utc, player_id, actiontype, entityname, entityid, itemstack_data, itemstack_encoding, x, y, z FROM entitylogs
            WHERE x BETWEEN @x - @radius AND @x + @radius
            AND y BETWEEN @y - @radius AND @y + @radius
            AND z BETWEEN @z - @radius AND @z + @radius
            ORDER BY id DESC
            LIMIT @loglimit
            OFFSET @skiplognum) e
            LEFT JOIN players p ON e.player_id = p.id
            ORDER BY e.id ASC";

            AddParameter(cmd, "@x", NpgsqlDbType.Integer, x);
            AddParameter(cmd, "@y", NpgsqlDbType.Integer, y);
            AddParameter(cmd, "@z", NpgsqlDbType.Integer, z);
            AddParameter(cmd, "@radius", NpgsqlDbType.Integer, radius);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/entitylog -r " + radius + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string entityname = reader.IsDBNull(5) ? "" : reader.GetString(5);
                        string entityid = reader.IsDBNull(6) ? "" : reader.GetString(6);

                        byte[]? itemstackData = reader.IsDBNull(7) ? null : (byte[])reader[7];
                        int itemstackEncoding = reader.GetInt32(8);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(9);
                        int logY = reader.GetInt32(10);
                        int logZ = reader.GetInt32(11);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {6} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4}({5}) " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{7}, {8}, {9}</font></strong>", timestamp, playername, playeruid, actiontype, entityname, entityid, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No entity logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendEntityLog");
        });
    }

    public void CheckEntityLogWithEntityID(int pageNum, IServerPlayer player, int groupId, string entityID) {
        QueueRead("check entity log by entity ID", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = EntityLogByEntityIdQuery;

            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityID);
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/entitylog -e " + entityID + " -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string? playername = reader.IsDBNull(2) ? null : reader.GetString(2);
                        string? playeruid = reader.IsDBNull(3) ? null : reader.GetString(3);

                        int actiontypeInt = reader.GetInt32(4);
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "UNKNOWN";

                        string entityname = reader.IsDBNull(5) ? "" : reader.GetString(5);
                        string entityid = reader.IsDBNull(6) ? "" : reader.GetString(6);

                        byte[]? itemstackData = reader.IsDBNull(7) ? null : (byte[])reader[7];
                        int itemstackEncoding = reader.GetInt32(8);
                        string? itemstack = DecompressText(itemstackData, itemstackEncoding);

                        int logX = reader.GetInt32(9);
                        int logY = reader.GetInt32(10);
                        int logZ = reader.GetInt32(11);

                        string playerStr = playername == null ? "" : "<strong>{1}</strong>({2}) ";
                        string itemstackStr = itemstack == null ? "" : "with {6} ";
                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | " + playerStr + "{3} {4}({5}) " + itemstackStr + "@ <strong><font color=\"#9BD1EC\">{7}, {8}, {9}</font></strong>", timestamp, playername, playeruid, actiontype, entityname, entityid, itemstack, logX, logY, logZ);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No entity logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendEntityLogWithEntityID");
        });
    }

    public (int, int, int)? GetLastEntityCoordsLog(string entityID) {
        const string operation = "get last entity coordinates";
        if (!TryBeginRead(operation)) return null;

        try {
            using var connection = dataSource.OpenConnection();

            using var cmd = connection.CreateCommand();
            cmd.CommandText = LastEntityCoordsQuery;

            AddParameter(cmd, "@entityid", NpgsqlDbType.Text, entityID);

            using var reader = cmd.ExecuteReader();
            if (reader.Read()) {
                int x = reader.GetInt32(0);
                int y = reader.GetInt32(1);
                int z = reader.GetInt32(2);

                return (x, y, z);
            }
            return null;
        }
        catch (Exception ex) {
            LogError("GriefLedger: Database read '" + operation + "' failed: " + ex);
            throw;
        }
        finally {
            EndRead();
        }
    }

    public void AddContainerLog(string? playername, string? playeruid, string actiontype, string containerid, string? itemstack, int quantity) {
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        QueueWrite((connection) => {
            long playerId = GetOrInsertPlayer(connection, playername, playeruid);
            var compressed = CompressText(itemstack);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO containerlogs (timestamp_utc, player_id, containerid, itemstack_data, itemstack_encoding, quantity, actiontype)
            VALUES (@timestamp, @player_id, @containerid, @itemstack_data, @itemstack_encoding, @quantity, @actiontype)";

            AddParameter(cmd, "@timestamp", NpgsqlDbType.Bigint, timestamp);
            AddParameter(cmd, "@player_id", NpgsqlDbType.Bigint, playerId == -1 ? null : playerId);
            AddParameter(cmd, "@actiontype", NpgsqlDbType.Integer, ActionTypeMap.TryGetValue(actiontype, out int val) ? val : 5);
            AddParameter(cmd, "@containerid", NpgsqlDbType.Text, containerid);
            AddParameter(cmd, "@itemstack_data", NpgsqlDbType.Bytea, compressed.data);
            AddParameter(cmd, "@itemstack_encoding", NpgsqlDbType.Integer, compressed.encoding);
            AddParameter(cmd, "@quantity", NpgsqlDbType.Integer, quantity);

            cmd.ExecuteNonQuery();
        });
    }

    public void CheckContainerLog(int pageNum, IServerPlayer player, int groupId, string containerid) {
        CheckContainerLog(pageNum, player, groupId, new List<string> { containerid });
    }

    public void CheckContainerLog(int pageNum, IServerPlayer player, int groupId, List<string> containerids) {
        QueueRead("check container log", () => {
            using var connection = dataSource.OpenConnection();
            int skipLogsNum = logLimit * (pageNum - 1);

            using var cmd = connection.CreateCommand();
            cmd.CommandText = ContainerLogQuery;

            AddParameter(cmd, "@containerids", NpgsqlDbType.Array | NpgsqlDbType.Text, containerids.ToArray());
            AddParameter(cmd, "@loglimit", NpgsqlDbType.Integer, logLimit);
            AddParameter(cmd, "@skiplognum", NpgsqlDbType.Integer, skipLogsNum);

            var logs = new List<string>();
            using (var reader = cmd.ExecuteReader()) {
                if (reader.HasRows) {
                    int backPageNum = pageNum > 1 ? pageNum - 1 : 1;
                    int forwardPageNum = pageNum + 1;
                    string pageCmdStr = "/containerlog -p ";
                    string backPageCmdStr = pageCmdStr + backPageNum;
                    string forwardPageCmdStr = pageCmdStr + forwardPageNum;

                    logs.Add("<strong><font color=\"white\">---------- PAGE " + pageNum + " ----------</font></strong>");
                    logs.Add("<strong><font color=\"white\">              <a href=\"chattype://" + backPageCmdStr + "\">←←←</a> | <a href=\"chattype://" + forwardPageCmdStr + "\">→→→</a></font></strong>");
                    while (reader.Read()) {
                        long tsSeconds = reader.GetInt64(1);
                        string timestamp = DateTimeOffset.FromUnixTimeSeconds(tsSeconds).UtcDateTime.ToString("yyyy-MM-dd HH:mm:ss");

                        string logPlayername = reader.IsDBNull(2) ? "Unknown" : reader.GetString(2);
                        string logPlayeruid = reader.IsDBNull(3) ? "Unknown" : reader.GetString(3);

                        string logContainerid = reader.IsDBNull(4) ? "" : reader.GetString(4);

                        byte[]? itemstackData = reader.IsDBNull(5) ? null : (byte[])reader[5];
                        int itemstackEncoding = reader.GetInt32(6);
                        string itemstack = DecompressText(itemstackData, itemstackEncoding) ?? "";

                        int quantity = reader.GetInt32(7);

                        int actiontypeInt = reader.IsDBNull(8) ? 5 : reader.GetInt32(8); // 5 is TAKEN
                        string actiontype = ReverseActionTypeMap.TryGetValue(actiontypeInt, out string aType) ? aType : "TAKEN";

                        string logString = String.Format("<strong><font color=\"#6F88DB\">{0}</font></strong> | <strong>{1}</strong>({2}) {6} {5}x{4} in <strong><font color=\"#9BD1EC\">{3}</font></strong>", timestamp, logPlayername, logPlayeruid, logContainerid, itemstack, quantity, actiontype);
                        logs.Add(logString);
                    }
                }
                else {
                    logs.Add("No container logs found.");
                }
            }

            Main.API.Event.EnqueueMainThreadTask(() => {
                foreach (var log in logs) {
                    Main.API.SendMessage(player, GlobalConstants.InfoLogChatGroup, log, EnumChatType.CommandSuccess);
                }
            }, "SendContainerLog");
        });
    }

    public void Dispose() {
        lock (lifecycleLock) {
            if (disposed) return;
            acceptingWrites = false;
            acceptingReads = false;
            databaseTasks.CompleteAdding();
            disposed = true;
        }

        workerThread.Join();
        readsDrained.Wait();
        databaseTasks.Dispose();
        readsDrained.Dispose();
        dataSource.Dispose();
    }
}
